### ISSUE TITLE
Video not playing in Baker

### ISSUE THREAD

**Issue by Appmantx** [Simbul/baker#1024]
I maked a video showing the problem I am having with Video. Could someone please help? Thank You http://youtu.be/eVpB-MlUqJY

**Comment by fturner19** [comment]
@Appmantx - I see you're using Hype to create some of your content. I would just use Indesign with the In5 plugin to create all your pages because it's more straight forward IMO...!

Here's a video explaining how to embed video into your Indesign pages. Hope that helps to point you in the right direction.
https://www.youtube.com/watch?v=1g0hZH5dgVE

**Comment by Appmantx** [comment]
Thank you for the video, I can get the html  ( video ) page to work 
outside of baker, just not when I test it in the baker project.

**Comment by folletto** [comment]
Same as #1033, you have already have the thread #1021 on the same subject, thus I'm closing this one. Please try to keep just one conversation on a single issue at time. :)

**Comment by justinputney** [comment]
If you're exporting from in5, it may be worth updating to version 1.5.4 or higher.

It looks like mediaelementjs and the Baker container do not play well together. As of 1.5.4, the in5 code detects the Baker container by checking the userAgent for "BakerFramework". If detected, in5 bypasses the mediaelementjs initialization and uses the native audio/video elements.
