### ISSUE TITLE
Download called twice

### ISSUE THREAD

**Issue by tekdope** [Simbul/baker#1054]
Hi guys,

I noticed something interesting while using Baker with MagRocket.
It seems that the Issue download is called twice when pushing the button. I talk with Andrew about this and we're agree to say that it seems to be a bug in the app.

To make it clear, if I tap on download, logs will show two calls and then MagRocket analytics will show two issues downloaded instead of one. Weird.

Has someone noticed something similar?

**Comment by blowback** [comment]
I think the first one is a HEAD request and the second one is the GET. I always see this pairing on my (non-MagRocket) server.

**Comment by nin9creative** [comment]
As Cedric mentions, I notice the download method seems to be getting called twice.  I noticed it before when I was seeing it double logged
in the the MagRocket System Log when in development mode, but now I'm adding some Analytics Logging to record various API interactions
and whatnot and it's definitely getting called twice.

I haven't had a chance to actually debug Baker yet...

**Comment by nin9creative** [comment]
@blowback You are right.  I didn't even think to check that, but since the Issue Download is happening, it make sense.

@tekdope - I made a change in the latest MagRocket-API code to ignore the HEAD request with respect to logging in the /ISSUE/ method.  I do still log the call as an "API Interaction" but don't count it as a download.  The stats should now be correct.  Each Issue download results in 1 increment in the Issue Download and 2 in the API Interactions.

You might want to grab that code and see if it works for you.

I think we can close this Baker issue now :)

**Comment by tekdope** [comment]
Hey Andrew, i will update the server and let you know.
I'm closing this since it's resolved.
