### ISSUE TITLE
Jitters in page scroll

### ISSUE THREAD

**Issue by amegalla** [Simbul/baker#108]
I have a small HTML page (34 K) that has some problems with baker:
1- The scrolling down (or up) is very jittery and slow
2- Page loading takes too much time

The only difference this page has is that it is using a right to left character set with Arabic encoding, otherwise the page has only text, not even a single Image.

Can someone help me with this problem!!!

**Comment by Xm4s** [comment]
Hi Amegalla,

seems like a rendering problem by iOS.

Could you send us the page in question?
We would like to see and test it, maybe we could come up with a solution :)

**Comment by amegalla** [comment]
Sure,

Here is the problem file:
https://gist.github.com/1078582/ea392ceecc72b9aea95e1964ed018638abcf7ace

**Comment by Xm4s** [comment]
Hi,

I've wrapped up your page in a simple html doc and tested it on both Baker and Safari:

• on Baker, while I didn't have any problem in scrolling the page up and down (the scroll was fast and smooth as usual) I saw that the rendering of the page took at least 6-7 seconds on my device (iPad 2). I think the problem is in the rendering of the arabic characters, in fact ...

• on Safari mobile the page seems to render much faster, almost instantly, but after that the scrolling of the page won't work for about 4-5 seconds.

I'm sorry, but I think the only solution here is to divide this page in multiple smaller pages, starting with two and going for more if the problem persists.

I hope this help.
