### ISSUE TITLE
Why doesn't the Baker template use xib or storyboard for UI?

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#1102]
Hi,

Wouldn't that make it much more user friendly in regards to UI design? Why has it been reduced to code view design only?

In regards to that, does anyone have a backer project with storyboards that they could share? That would be awesome, thank you.

**Comment by folletto** [comment]
Hello. :)

We actually started Baker using XIBs. It would have been a lot easier, if only it was possible. I don't recall in detail all the things that required us to move away from them, but ultimately XIBs work well as long as your app follow a set of rules and use a set of classes, and Baker due to its HTML nature breaks pretty much all these rules.
We tried at first to keep XIBs and add the rest on top, but again that meant having instances when you didn't know if the action you were supposed to modify was on the XIB or in the code, transforming simple edits in hunts that took twice the time.

In the end, abandoning XIBs made everything easier and more maintainable. We'll bring them back when it becomes feasible. :)
