### ISSUE TITLE
Disable screenshots 

### ISSUE THREAD

**Issue by albertora** [Simbul/baker#1107]
Hi,

I'm looking in web any way to disable screenshots on iPad and I found that in IOS 7 it's not possible.  Anyone can help me? Has Baker any option for this?

**Comment by folletto** [comment]
Hello there :)
What do you mean by "disable screenshots"? If you mean Baker's screenshot mode, you can just switch to three-cards mode. If you mean iOS screenshot, there has never been a way to disable them.

**Comment by albertora** [comment]
Yes, I mean IOS screenshot. 
I have found this article http://theultimatedeveloper.blogspot.com.es/2013/03/how-to-disable-automatic-snapshot-in.html for prevent screenshots in phonegap, and I have thought that maybe with baker too it's possible.

**Comment by folletto** [comment]
That's an internal screenshot used for animation... I guess you could do the same with Baker if you want, doesn't seem that PhoneGap specific. 
But... it feels quite and extreme and ineffective measure: may I ask what are you trying to achieve?

**Comment by albertora** [comment]
I'm working on a pay ebook and my client doesn't want that anyone can make page screenshots.

**Comment by folletto** [comment]
Well... a few points then... :)
1. That hack above won't solve the issue. It just avoids an internal Apple routine (protected by default) to do its work (that is, animating the properly the page).
2. It's not possible to avoid screenshots on iOS, afaik. Screenshots are provided by the operating system and can't be blocked at the application level.

Thus: your client is asking for something that's not possible to achieve. Plus, I'd say that's a pretty serious level of paranoia, because screenshots are really the last thing they should worry about, there are much many other things that could be done, and these kinds of protections never worked. Ask the music or movie industry. ;)

**Comment by albertora** [comment]
Ok thank you so much :)
