### ISSUE TITLE
Seeking reference/tips for surveys/quiz problems

### ISSUE THREAD

**Issue by Maxhodges** [Simbul/baker#111]
Hi I'm new to github and just getting started with baker/laker framework and wondered if anyone may be able to refer me to any code reference or samples for surveys/test questions?

I'm new to JavaScript but I'm an experienced VB.NET programmer so hope I can pick up jquery stuff quickly. I'm working on some projects for people who are learning foreign languages. So I'm nterested in anything related to quizzes, tests, surveys - textbook type stuff. 

Very Kind Regards,

Max

**Comment by Xm4s** [comment]
Hi Maxhodges!

I'm sorry but I haven't understand if you need to have the results of your quizzes/survey directly in the application or on a remote server.

In the first case you'll need to implement a way to actually save/load data from the html page in the application, since web pages are reloaded every time the user swipe to another page. I'd probably look into HTML5 local storage feature or in a SQLite database.

In the second case you will need a server to handle the user data, then a simple js ajax call when the user "submit" his answers should do the trick, but of course this would work only if the device is connected to the net.

Unfortunatley I haven't got any specific example or tutorial for you, but you can find a lot of good ones for both cases on google.

Well, if you want to learn jQuery you can look at http://jqapi.com/, an alternative and well organized jQuery documentation which I've found very useful :)

**Comment by folletto** [comment]
Hi!
Given there's no follow up we'll consider this as closed, if you have other questions just write here. ;)
