### ISSUE TITLE
/CONFIRMPURCHASE API call - how can I cause Baker to show an error message that the receipt couldn't be validated?

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#1119]
I'm about ready to poke my eyes out in trying to figure out what is going on.

I have a few different devs having an occasional problem when the /confirmpurchase process seemingly fails and either a paid subscription doesn't unlock or a single issue purchase doesn't turn from "Buy" to "Download"

I've tracked the error to the /confirmpurchase method and the verifyReceipt method call that validates the receipt with Apple.  It seems that in some random cases, the Apple receipt validation call doesn't return a valid JSON Receipt object which then causes MagRocket to bomb on adding the Receipt / Mark Issue(s) as purchased.

So seemingly from an end user perspective, it worked - just things don't get unlocked.  On the MagRocket backend, there is no record of the purchase - just an error in the SYSTEM_LOG table.

Trying to figure out the best way to approach this!  Wondering if anyone has seen this behavior?

And for the Baker guys, is there a response I can provide back to Baker from the /ConfirmPurchase call that will cause Baker to show some sort of error message that says that the Receipt validation failed or something?

**Comment by Simbul** [comment]
Purchases on the App Store follow a transactional model:
1. You purchase something within Baker and get a receipt - this creates a _transaction_ object
2. Baker sends the receipt to the server (request)
3. The server checks the receipt
4. The server unlocks content
5. The server tells Baker that content was unlocked (response)
6. Baker finishes the _transaction_ by calling the App Store and confirming everything is ok

Steps between 2 and 5 are contained in the request/response cycle for the call to `PURCHASE_CONFIRMATION_URL`.
If at any time during the 6 steps something goes wrong, Baker does not finish the _transaction_. This means that, the next time the app is started, steps 1 to 6 will be attempted again. This should make absolutely sure the user never pays for something they cannot receive (though it might not be the best user experience).

I've just tested by having my `PURCHASE_CONFIRMATION_URL` endpoint return a status 400 (instead of 200) and this alert is displayed:
![ios simulator screen shot 10 sep 2013 23 48 34](https://f.cloud.github.com/assets/147104/1119037/628d452e-1a6b-11e3-88d8-5506041fbef8.png)

**Comment by nin9creative** [comment]
Ok, actually got to the same point about an hour ago :)

Thanks!
