### ISSUE TITLE
Difference between issue ID and book ID for analytics purposes

### ISSUE THREAD

**Issue by bdgeyter** [Simbul/baker#1145]
For analytics purposes, it's handy to track when an issue is opened and when it is closed. 

The opening notification has access to the issue (and book)

However, the closing event is called from the `BakerViewController`, which only has access to the `BakerBook *book` property. 

The problem is that the `book.ID` and `issue.ID` do not match, which makes it hard to log events in Google Analytics tracking the opening and closing consistently. 

Using only the `book.ID` is also not a good solution, since this seems to be unique for every user.

I think the best solution would be to give the `BakerBook` a `BakerIssue` property. Any other suggestions?

**Comment by bdgeyter** [comment]
Since I'm guessing you want `BakerBook` to be unaware of Newsstand, I found another solution. 

Here's a category on `IssuesManager` that does the trick:

```
#import "IssuesManager+IssuePath.h"

@implementation IssuesManager (IssuePath)

- (BakerIssue *)issueForPath:(NSString *)path{
    for (BakerIssue *bakerIssue in self.issues) {
        if ([bakerIssue.path isEqualToString:path]) {
            return bakerIssue;
        }
    }
    return nil;
}

@end 
```

This way you can use the book.path to track back to the issue.ID.

**Comment by Simbul** [comment]
You're right, the behaviour of `BakerIssueOpen` and `BakerIssueClose` is not very consistent.

The cleanest solution would probably be to pass in the `IssueViewController` instance in both cases (instead of passing in the `BakerViewController` instance for the latter event).

That would require some nontrivial refactoring of the analytics component, however. In addition, you already found a workaround, so we'll close the issue - but thanks for pointing this out!
