### ISSUE TITLE
Version 3 of Laker

### ISSUE THREAD

**Issue by dixiepnum** [Simbul/baker#115]
Hi,

Any updates on the timing of Laker Version 3?

**Comment by tablazines** [comment]
Interested in knowing if it's right around the corner as well. My publication should be finished next week. Should I wait for Baker 3.o?

**Comment by dixiepnum** [comment]
Also need to know who's building it....eg will it be rock solid and bug free?

**Comment by folletto** [comment]
We'll always work to ensure that's as much as possible solid and bug free, of course. But being an opensource project you can download it right now, test it, and tell if you can find bugs. That's the best way to ensure a great product. :)

We slowed down a bit now, since a few of us are on holiday, but in september we should be out with Baker 3.0, that incorporates all the code-level changes made in Laker (plus more) so you don't have to compile a different codebase anymore: it's just Baker (Objective-C) and Laker (HTML/CSS/JS).

If you have any doubt, please tell us! :)

**Comment by dieter74** [comment]
Hello--
We're working on a magazine for iOS devices, and rather than start from scratch, wanted to hook up with an open source project and contribute.  I've just started doing the research into this, and watched the Newsstand video from WWDC. 

I'm curious as to what the major changes are for Baker 3.0.  I couldn't find a roadmap or blog post about it.  If it exists, could you point me to it, or could you give me a high level overview?

The main thing that we would need in baker would be newsstand integration, and hopefully, if its possible, the NKLibrary support for multiple issues.  We plan to publish future issues on AWS or some web service, do a push notification so our subscribers can download the next issue.

This is all code that I'm comfortable writing and contributing to Baker, or if you've already started on a solution, I'm happy to jump in and help/debug/extend. 

I couldn't find a 3.0 branch of baker.... so I'm guessing it is in the head?

If you think NewsstandKit integration, and Library integration don't make sense (e.g.: baker is meant for books) then I can fork, or do my own thing.

Thanks--

**Comment by dixiepnum** [comment]
Hi,

Sounds like you have lots of priorities and issues. I am trying to launch to newstand by November for Christmas, so it would be good to keep in touch.

Regarding your points...

. someone originally posted about Baker 3.0, but there were no specs included...
. I posed the question on github regarding dates and specs for both upgrades: Baker and Laker
. I got a response from Florian suggesting that both would be coming, Laker after Baker, that would include more xcode for navigation etc, as well as testing. But no dates or specific content were listed
. NK integration seems pretty simple. I think there is a github thread outlining it. There is a free apple video explaining it. There's only 4 or 5 properties to set
. the challenge of multiple issues and library was taken on by an existing contributor and there is a specific thread on github for it. I haven't heard anything though about its integration to the Baker and Laker upgrades.
. at this point, I believe library is a separate issue from NK. I was leaning towards creating a library simply based on multiple views, dead simple in xcode. But I have no idea when ios will crap out due to memory size issues. I mean, can 1 app handle 100 chapters of html5, each with 5,000 words of content and 20 jpegs? Laker loads 1 chapter at a time, so why not?

So the status is still a grey area. If there's no news on the upgrades by September 4th, I am going to dig into xcode to customize my magazine app based on the older Laker. I will share my code on github as I go...feature by feature...but I would prefer to save time with Baker/Laker 3.0...

**Comment by folletto** [comment]
@Dieter
The roadmap is open and discussed right here. :)
Check all the open issues, the discussions there and, probably most of all, click on "Milestones" at the top of the page. :)

The 3.0 is the current head, will be 3.0 once released before we move to 3.1. :)

Also, please, read the related issues for Newsstand and Library and help us directly. It makes sense, it's just a matter of developing it and integrating. Right now we are in the middle of a big optimization push, but for everything else please let's collaborate and improve this one. 

To give you a couple of pointers, the discussion about Newsstand is Issue #100, and the one about the multi-book is Issue #20.

**Comment by folletto** [comment]
@dixiepnum
1. Baker 3.0 specs are on the Milestones page above. :)
2. For Laker you should refer to Florian, I'll ping him since we are talking a lot so he can give you his answer. :)
3. Yes. We are an opensource project with limited resources, and Florian too. So we aren't able to set dates, but we are trying to stick to some indicative timelines. It's hard, but usually we are able to do it. This time we are aiming for a september release for Baker 3.0, we can't assure it, but it's feasible given we don't hit any other nasty bug. :)
4. Yep, I was checking it and looked simple. I'm still not sure if we have to build the multi-book support before integrating with Newsstand however. But let's move that discussion on Issue #100. :)
5. That issue is what we have, so exactly like you we don't have any other news. We checked the forked tree he was working on, and while improved, it's still not complete to be integrated back into Baker, so we are waiting until either someone does that, or we are going to do it ourselves (Baker 4.0, I suppose).
6. Yes. With baker you should be able to work easily with an arbitrary number of pages (given hw limitation hehe). That's not an issue. :)

If you feel we aren't working as fast as you'd like, I can suggest that you'll work with us instead of forking it, so we can build a better tool for anybody. In that case just keep us updated and start forking from master. If we are able to collaborate we'll be stronger together. :)

**Comment by dixiepnum** [comment]
Thanks! Happy to work with....will read up on the details...

**Comment by tablazines** [comment]
@dieter74 
There's a sample of the multiple issues work in progress here: http://www.siteless.org/?p=585

**Comment by folletto** [comment]
Yes unfortunately that's a fork, and it's not Baker judging from the code. If you check the fork tree here on github you'll see the other fork with the multi-issues work. :)

**Comment by tablazines** [comment]
oh? Ok.. cool.

**Comment by nin9creative** [comment]
So has anyone got the Laker starter kit working on the Baker 3.0 code?  Is that supposed to work somehow?  I'm looking to start a new magazine/eBook and I want to use the latest Baker code, but love the HTML/CSS stuff that the Laker demo app has going on...

**Comment by dixiepnum** [comment]
Google baker 3.0....they have a new xcode project to download.

**Comment by nin9creative** [comment]
@dixiepnum 

I know that there is a Baker 3.0 xcode project.  I guess I'm asking will the out of the box samples for Laker work with the newest Baker code?  Or if I want to start a Laker project right now I still need to use their modified version of the Baker 2.0 framework?

Was wondering if there was any in flight work to create a version of Laker that works on the 3.0 framework, or if the intention is that Baker is sucking in the changes that Laker has created?

Just a little confused on the relationship of the two projects etc.

:)  Although it seems that it doesn't take much to confuse me lately!

**Comment by dixiepnum** [comment]
As far as I'm concerned, the downloadable xcode project should have the updates on both sides baked in. But if you want, just follow the step by step instructions on the site.

**Comment by folletto** [comment]
LOL! :D

Well, I can't answer for Florian, but we built Baker 3.0 including all the features that he added in Baker 2.0 to make its Laker release (plus more, of course). In my opinion, with Baker 3.0 onward we should have:
1. Baker as the Objective-C part (Xcode)
2. Laker as the HTML/CSS/JS part (Hpub book/ folder)

In this way we are going to build each other on our respective strengths keeping a clean separation and upgrade path for all our users. :)

**Comment by dixiepnum** [comment]
Right, so if you just download the new xcode project on the baker 3.0 site, it should have both baked in...correct?

**Comment by folletto** [comment]
On Laker website, yes, because he builds over Baker Framework code. :)

**Comment by ffranke** [comment]
Hey guys, 
I'm going to update laker next week, I'm totally busy right now...

cheers
florian

**Comment by Simbul** [comment]
Cool. Feel free to open a new issue to let everyone know when the new version is released :)

**Comment by folletto** [comment]
Laker has been updated to version 1.2 with full Baker 3.0 support by the awesome @ffranke. :)

More info here: http://www.lakercompendium.com/2011/12/27/laker-1-2-and-a-few-notes/
