### ISSUE TITLE
Problem updating the issues with language change

### ISSUE THREAD

**Issue by nickiscoding** [Simbul/baker#1156]
Hi,
I'm setting up a localized version of a magazine using the shelf model.

I created a variable in the localization file that points to shelf.json file for each language (es: shelf_en.json / shelf_it,json)
"NEWSSTAND_MANIFEST_URL = "http://example.com/en/shelf.json";

edited Constant.h to point at that localized variable
# define NEWSSTAND_MANIFEST_URL NSLocalizedString(@"NEWSSTAND_MANIFEST_URL",nil)

PROBLEM

All is working ok, once I change the language in the device I see the different covers on the app issue page. 
(also the issue preview image is updated automatically)

The problem is coming out when I click on the issue, the app still load the previous downloaded one. 
only if I delete the issue and re-download it I see the right language version.

I't like there was a sort of cache in the dowloaded issues shelf, but : the json that is pointing changes for every language and the .hpub file is also different on a different url.

Wondering how to correct this issue.

Thanks!

**Comment by Simbul** [comment]
That's not a sort of cache, it's simply how Baker works ;)
The assumption is that unique issue `name`s in the shelf will point to the same file. Of course if the shelf JSON breaks the assumption, Baker will get confused.

Have you tried assigning different names to the different localisations of the same file?

**Comment by nickiscoding** [comment]
Yes, the two shelf.json have inside books with different names that points to different .hfpub files ... I also set different dates to the single books. changing language and launching the app  all changes (also the cover image linked in the json)  but the link to the downloaded publication won't change. 

The get the right pubblication (after a change of language on the device) you have to delete and then re-download the publication. 

Another thing: if you are in the english device language and download a pubblication (of the shelf_english.json)  once you change language ex italian (in shelf.json)  the app update the view of pubblications but sign the publication as downloaded and linked to the previus language. 

thanks for help!

**Comment by osmartbm** [comment]
Hello!
Have you solve the problem?
I have a similar issue with my app.
We already have the app in the app store.

Our magazines are in English and Spanish.
The app was configured to display the magazines according to the ipad language, so if you are in english the shelf displays the english magazine.
Also we have two instalations of magrocket controlling each language.

The problem comes when the user change the language of the ipad.
The subscriptions or the purchases works well in one language, the user can purchase an issue or subscribe as well, but if they change the language of the ipad, the subscriptions stop working, they are asked to subscribe again, and if they subscribe again the "PURCHASE / DOWNLOAD" button doesnt work.

So they cant download or purchase the magazine.

And if the user change again the ipad language, the magazine the already purchased in one language has been deleted or archived (i mean that they have to download it again). They can downloade it again with no cost.

I dont know where is the problem or what should i have to do to make it work.

Can anyone please help?

Thank you very much.

**Comment by nin9creative** [comment]
Well if you have two different instances of MagRocket then that's probably part of the issue...  The purchases available are tracked and controlled by the MagRocket...

So I can see where switching languages would cause a problem...

Regards,
Andrew

**Comment by osmartbm** [comment]
Thank You Andrew
But if i have two different shelf.json controled by two different MagRocket what can be the problem?
I mean than they are installed in two different subdomains how can they know each other?
Baker has the configuration 

#define NEWSSTAND_MANIFEST_URL NSLocalizedString(@"NEWSSTAND_MANIFEST_URL",nil)

With all the URLS pointing to their respective subdomains.

and in spanish we have the one MagRocket 
and in english another different.

I´ve been wanting to talk to you regarding a posible help on different issues about the  Magrocket instalations, can we talk via telephone or email?

Thank You very much

**Comment by nin9creative** [comment]
Maybe I am misunderstanding the problem.

Are you expecting that an issue purchased in English on one MagRocket installation to also show up as purchased
on the other MagRocket installation when the user switches back to Spanish?

Andrew

**Comment by osmartbm** [comment]
No Andrew, i want to sell separetly the magazines.

The people who have an iPad in english language, they purchase only the English version of the magazine.
The people who have the ipad in spanish they purchase only the spanish version.

In the localized strings section, where we translate all the posible variables, like this:

---

In the Localizable.strings (Spanish) file we have:

"NEWSSTAND_MANIFEST_URL"  = "http://api.mysite.com/issues/:app_id/:user_id";

"PURCHASE_CONFIRMATION_URL"  = "http://api.mysite.com/confirmpurchase/:app_id/:user_id";

"PURCHASES_URL"  = "http://api.mysite.com/purchases/:app_id/:user_id";

"POST_APNS_TOKEN_URL"  = "http://api.mysite.com/apns/:app_id/:user_id";

---

In the Localizable.strings (English) file we have:

"NEWSSTAND_MANIFEST_URL"  = "http://apien.mysite.com/issues/:app_id/:user_id";

"PURCHASE_CONFIRMATION_URL"  = "http://apien.mysite.com/confirmpurchase/:app_id/:user_id";

"PURCHASES_URL"  = "http://apien.mysite.com/purchases/:app_id/:user_id";

"POST_APNS_TOKEN_URL"  = "http://apien.mysite.com/apns/:app_id/:user_id";

---

And in the Constants.h we have set:

#define NEWSSTAND_MANIFEST_URL NSLocalizedString(@"NEWSSTAND_MANIFEST_URL",nil)
#define PURCHASE_CONFIRMATION_URL NSLocalizedString(@"PURCHASE_CONFIRMATION_URL",nil)
#define PURCHASES_URL NSLocalizedString(@"PURCHASES_URL",nil)
#define POST_APNS_TOKEN_URL NSLocalizedString(@"POST_APNS_TOKEN_URL",nil)

---

As you can see we install two different MagRockets, one for each language.

We also set in iTunes Connetc, four In-App Purchases:

1 for the spanish version of the magazine
1 for the english version of the magazine
1 for a 6 months subscription
1 for a year subscription

---

Here is the app in the App Store:

https://itunes.apple.com/us/app/travel-by-mexico/id723184895?l=es&ls=1&mt=8

The problem is:

If I have the ipad in spanish, and I can purchase and/or subscribe to the magazine ok, but if i change the language in the ipad to english,  i can not purchase the english version of the magazine. we try to do it, but when we tap PURCHASE button, it doesnt change to DOWNLOAD after the purchase. 

Also when we return the ipad to spanish the app deletes the already downloaded magazine in spanish, so we have to download it again. 

---

Also we have other issues regarding the MagRocket installations but we want to talk to you so we can explain it better.

Thank You very much for your time.

Also:

Travel By México is a company who has more than 15 years supporting the tourism in Mexico.
We have to sell the magazines because we also have a Foundation who supports the children in Chiapas, so we get the money from our banners in the website and now we hope in the Newsstand.

**Comment by nin9creative** [comment]
Are you expecting the users to be switching their language versions after the app is installed?

I would think that a better "test case" would be to setup the iPad with the language prior to installing
the app on it for testing.

I don't know what issues are specifically being caused by swapping the language after some purchases
have already been made.

However the "deletes spanish magazines" behavior that you note - I think that even if a user has an issue
downloaded and then it is removed or doesn't show up in the shelf JSON, it dissapears.  At least I know that
was the case in the past - I don't know if that behavior changed in more recent Baker releases.

What version of MagRocket are you using?

You may want to go into the API and add some debugging log messages to the SYSTEM_LOG table to see if you
can log some more information that may be helpful in figuring out the root cause of the issue.

Andrew

**Comment by nickiscoding** [comment]
Hi, 
sorry for my delay in that answer, I've been a bit busy. 
The problem I've reported was related to the simulator, testing the app on the real device my problem flew away.

I'm not using magrocket at the moment, I'm using a self-made system to manage the issues.

**Comment by folletto** [comment]
Hi @nickiscoding, could we consider this issue closed then? :)

**Comment by nickiscoding** [comment]
Hi @folletto , at my side all is solved, so we can close this issue, but maybe can be useful for @osmartbm keep it open for his issue?

**Comment by folletto** [comment]
Thanks. :)

We'd like to keep one issue open specifically for the issue at hand, otherwise issues are hard to answer and hard to search. So if there's still need, @osmartbm can open a new issue specifically for the problem at hand. :)
