### ISSUE TITLE
Google Analytics: update for v3?

### ISSUE THREAD

**Issue by fobetor** [Simbul/baker#1171]
Hello,
 Since the google analytics api v2 for which the wiki is no longer available and legacy, Can some one write an update for v3?
 I'm not a programmer, and I can just make little changes in code, and I have modified a little bit the basic baker one, but... I'm lost, I cant make analytics recognize the category, action or label ... since it seems it is necesary to make a dictionary or something else... ????
Changes to make with v3:
a) include in BakerAnalyticsEvents.m
# import "GAIFields.h"
# import "GAITracker.h"
# import "GAIDictionaryBuilder.h"

b) the call in receiveEvent should be now:
tracker send:[[GAIDictionaryBuilder createEventWithCategory:@"action"
                                                              action:@"open"
                                                               label:@"EVENT"
                                                               value:[NSNumber numberWithInt:100]] build]];

... BUT... in analytics, all parameters appears as "undefined"

Some help please?

**Comment by MrKistic** [comment]
Hi @fobetor,

I implemented v3 yesterday, there's not a big difference in the code, just the using the DictionaryBuilder to create the event details as you've outlined in b).

As a very simple example, here's my code for tracking the `BakerApplicationStart` event:

```
// Track here when the Baker app opens
[tracker send:[
  [GAIDictionaryBuilder createEventWithCategory:@"action"
                        action:@"open_app"
                        label:@"Newsstand App Open"
                        value:nil]
build]];
```

I'm seeing this as a valid event within Google Analytics and it has the correct label applied.

All I did was follow the instructions here:

https://developers.google.com/analytics/devguides/collection/ios/v3/

which aren't too much different from what's on the wiki. Just make sure you included all of the files and libraries in your project. Otherwise that's all I did to get it working. Hope that helps some.

**Comment by fobetor** [comment]
Thank you @MrKistic  , it seems the same code I'm using except for "value" param. I cant see the correct label in GA, it appears as "undefined".
 I dont know why....

**Comment by folletto** [comment]
I updated the tutorial to Analytics SDK v3.0: 
https://github.com/Simbul/baker/wiki/How-to-setup-google-analytics-or-similar

Have a look to see if it sounds correct please. ;)

**Comment by MrKistic** [comment]
Looks pretty good so far.

For V3 though, you will also need to include `#import "GAIDictionaryBuilder.h"`.

The only other thing might be that you have `action:@"open"` for each event, which would more likely be different for each event. For example, I've got `action:@"ViewPage"` for the `BakerViewPage` event, and then use the `label` property to pass meaningful data, like `label: [NSString stringWithFormat: @"%@ : %d", bakerview.book.title, bakerview.currentPageNumber]`. Otherwise all of your `ui_action` event actions will just be listed as `open`.

Also is it worth mentioning Screen Names in the wiki or is that more than required?

https://developers.google.com/analytics/devguides/collection/ios/v3/screens

As an example, I set the Screen Name to "Home Screen" in `BakerApplicationStart` and `BakerIssueClose` and then  to the Issue Title in `BakerIssueOpen`. It's good for a quick reference of how many times an issue is viewed or for Real-Time stats if nothing else.

**Comment by folletto** [comment]
I didn't find `#import "GAIDictionaryBuilder.h"` mentioned in Google's tutorial, I thought it was automatically included by `GAI.h`... Is it missing? Or a requirement just for Events?

What you say makes sense, however as you pointed out, the objective of the wiki page is just to get it started. I don't want to replicate all Google's documentation, keeping that up to date would be quite a work by itself. :)

That said, if you feel there are changes that would make the tutorial simpler and more understandable, then please feel free to edit the page directly. :)

**Comment by MrKistic** [comment]
No, it's not automatically included which is kind of annoying! You only need `GAI.h` to initialise the tracker, but to create and send the event data it uses `GAIDictionaryBuilder`. That's in the events documentation, they just neglect to tell you that you need the header too. There's an example of it in the Advanced Configuration page but that's about it.

As for the rest of it, it's probably confusing enough as is without throwing Screens and the rest into the mix :) If I can think of a simple way of adding a bit of extra info I may do it, perhaps an advanced GA section.

**Comment by folletto** [comment]
I see! Thanks for the explanation. :)

Then I'll close this issue, we should be all set. :)
