### ISSUE TITLE
Encrypting Resources of Baker Issue

### ISSUE THREAD

**Issue by yozehariando** [Simbul/baker#1188]
Hi and thanks for this great framework.

I'm in the middle of building a standalone app using Baker. Since the app using in-app purchase, I need to encrypt the resources as requested by my clients.

I've read the AES method to encrypt the file but i'm a bit lost to implement this method in Baker. 

I really appreciate any help or guidance for my problem.
thank you..

**Comment by folletto** [comment]
Remember that "encrypting" will do very little, because it still will be decrypted on the device, and the key to decrypt will be on the device itself as well, thus both of them are accessible. It will make any intrusion just slightly more difficult, at the cost of a really complex development. I personally would try to clarify this to the client as clearly as possible.

I think you should ask on StackOverflow or other resources. That's something you are adding on top of Baker and that's pretty independent on the fact you're actually adding it on Baker.

Considering also that Standalone mode doesn't support downloads, this is a pretty heavy development. I'm sorry.
