### ISSUE TITLE
Bug in Baker 4.2 when swiping pages.

### ISSUE THREAD

**Issue by codegeek511** [Simbul/baker#1208]
I was swiping through the pages of my magazine and then suddenly i had to swipe twice to get to the next page. Has this happened to anyone else? Also is there a way i can fix it? Lastly could have been my iPad having a glitch and not the app?

**Comment by folletto** [comment]
It's very difficult to say from the description you give.
What happens? What do you mean to "swipe twice to get to the next page"?

Could you please go through [Problems and Debugging](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) and report back, including a video that shows the issue?

**Comment by albertora** [comment]
Hi, 
I've the same problem, since I've updated to version 4.2,  I swipe on some pages and the first time doesn't works, the page makes a little bounce, at the second time the page swipes ok. Were you able to fix this problem?

**Comment by albertora** [comment]
Ok, the problem seems to be, in my case, a div bigger than the page without overflow hidden. Now all works fine.

**Comment by calaba** [comment]
Had same/similiar issue - only while swiping right to left (go to next page on right side). The problem was caused due some CSS style clashes. I was also using Laker Compendium on top of Baker. And I used one of my styles with HTML body tag (<body class="mystyle">) .. after removing the body-tag style - all start working fine ..
