### ISSUE TITLE
Video in Landscape when App restricted to portrait only?

### ISSUE THREAD

**Issue by ffranke** [Simbul/baker#128]
Hey there,

I restricted the App to Portrait only. The fullscreen-view of the videos when played do also not support landscape. Is there a way to restrict the pages and the app to portrait, but not the video?

Thanks!
Florian

**Comment by folletto** [comment]
Uhm. It might be a byproduct when we add the manifest book.json support.

We'll check :)

**Comment by ffranke** [comment]
Do you know the code that has to inserted into the xcode files? That would help me also! ;)

**Comment by folletto** [comment]
Uhm not really, because it's just a guess, and if we had the code we probably would have that already in place ;)

However that could be possible because right now the lock is at package level, instead for manifest we might move the lock to code level and being in the code it should be possible to dynamically enable or disable it.

**Comment by Xm4s** [comment]
I'm sorry but if an app is restricted to Portrait only the lock applied also to all the videos, even if they are played in fullscreen.

Currently orientation lock work right this, I can't think of a different way to implement it to handle fullscreen videos.

**Comment by ffranke** [comment]
allright! Thank you!

**Comment by folletto** [comment]
I'll close this but... of course, if you find someone that has the solution or if you find that solution yourself, ping us that we will implement it. ;)
