### ISSUE TITLE
Video keeps playing even after page change

### ISSUE THREAD

**Issue by ffranke** [Simbul/baker#129]
Hi!

When I start a video and continue to the next page, the video keeps playing in the background.

cheers
florian

**Comment by folletto** [comment]
Yeah, that's a problem with page caching, it's the mirror problem of Issue #122

**Comment by folletto** [comment]
In Issue #27 we have now removed the three cards feature in favor of the dynamic image caching. We'll de-scope Issue #122 and this one since it's not critical anymore for 3.0 release — Mostly because it could be almost impossible to fix this in any other way.

When we'll implement Issue #122, if three-cards flag is turned on then you could remove the video as well, so it shouldn't be a problem in either way.
