### ISSUE TITLE
Opinions asked about support iOS 4.3 / 5.0

### ISSUE THREAD

**Issue by danielbenjamins** [Simbul/baker#138]
This question hasn't anything to do with Baker itself, but is about Safari (on which Baker relies for rendering pages).
Will you let your apps support iOS 4.3 when iOS 5.0 comes out this fall?

Because iOS 5 will include a more recent version of Safari, there will be more support for new features and CSS3-support.
The problem is, some of these functions will not work or will look ugly in iOS 4.3.

I'm thinking about only supporting iOS 5 for an app I'm creating at the moment, but I'm not sure yet.
What are your thoughts about this?

**Comment by folletto** [comment]
That's a really good question, I never thought about that. :)

In theory, Baker just uses the WebKit engine provided by the OS, so, probably, it will use the more recent version on iOS5 and the older one on iOS4.x, but I can't tell it for sure.

Usually, I would advise to use the same web fallback techniques if you need to use more advanced features, in order to have a magazine on all the devices, and a better looking / working one on the latest version.

I'm asking a few friends, let's see if I can get a better answer. ;)

**Comment by folletto** [comment]
Ok, the answer I received is that the engine gets updated with the iOS, so if you really need to use advanced features add some kind of graceful fallback. :)

What kind of feature are you thinking of? :)

**Comment by danielbenjamins** [comment]
Well, not huge features, but I was struggeling for some minutes why the "box-shadow" rule (CSS) did work in Safari Desktop and not working in the iPad Simulator (iOS 4.3). The fallback "-webkit-box-shadow" works in both, so no problem at all :)
Also some HTML5 features don't work well yet in iOS 4.3, like (figure) and (figcaption). Just small features which can be solved very easy, but this made me thinking about supporting "older" devices.

**Comment by folletto** [comment]
Ok, that's clear. :D
