### ISSUE TITLE
just checked the transition between pages of books published on apple stores

### ISSUE THREAD

**Issue by robo8** [Simbul/baker#147]
Hi all,

I am a newbie and very excited about Baker and excited to get started on my project.
I am a special education teacher and I want to make interactive book.
I bought/downloaded some books in the showcase of Baker site... just to see them in action. 
And I noticed the white blank page with page numbers every time i turn pages.....  can you make your projects without them? They still look good but sometimes they slow down the transition....  and how do i hide the page scroller and make it pop out like in some books?  Thanks for your help in advance.
Best,

Chris

**Comment by folletto** [comment]
We are trying to address that problem in the upcoming 3.0 release, however it's a problem related to the limited resources on the iPad (CPU, RAM) and the weight of the HTML browser (UIWebView).

I don't understand instead the question about the scroller: it should be already hidden and appear only when you scroll. What do you mean exactly? :)

**Comment by robo8** [comment]
I was talking about navigator... actually...  some books show scroll bar (page navigator) at the bottom (when tapped ) to help navigate from page to page or skip pages.... but I noticed that some of those books do not seem to have page navigator at the bottom....  and some books don't let you zoom in and zoom out their content ...  If i want to include these functionality and interactivity, where can I find the sources?

**Comment by folletto** [comment]
In the upcoming release, or in the current GIT Master, the navigator feature is automatic and appears when you add a file called "index.html" to your book. :)

The zoom instead is disabled by default, since it would be better for you to implement the zoom you need through javascript, but you can re-enable it if you really want this functionality. In Baker 2.0 (the released version) you can do this by editing this line: https://github.com/Simbul/baker/blob/2.0/Classes/RootViewController.m#L47 :)

**Comment by robo8** [comment]
Thanks :)
