### ISSUE TITLE
Zoom In / Zoom Out

### ISSUE THREAD

**Issue by venkatmarri** [Simbul/baker#149]
Hi,
I have used baker frame work for our magazine... 
(http://itunes.apple.com/us/app/qatar-today-magazine/id465046546?mt=8)
Its working fine, except while swipe back, its takes time to move page... its sometimes irritating...
and users wants the page zoom options.. how to enable zoom using xcode...
or any other solution for this...

thanks

**Comment by folletto** [comment]
Are you using Baker 2.0 or the latest in-progress master from GitHub? :)

**Comment by venkatmarri** [comment]
Using Baker 2.0

**Comment by folletto** [comment]
I'll take then the answer from issue #147: The zoom is disabled by default, since it would be better for you to implement the zoom you need through javascript, but you can re-enable it if you really want this functionality. In Baker 2.0 (the released version) you can do this by editing this line: https://github.com/Simbul/baker/blob/2.0/Classes/RootViewController.m#L47 :)

**Comment by venkatmarri** [comment]
Thank You

**Comment by folletto** [comment]
You're welcome :)
