### ISSUE TITLE
Permanent screenshots

### ISSUE THREAD

**Issue by Xm4s** [Simbul/baker#160]
Screenshot should be saved in a permanent directory instead of the app cache directory

**Comment by danielbenjamins** [comment]
Do you think it could be possible to let the user make a screenshot for e.g. a drawing (#142) they made? And eventually share it on Twitter or Facebook?

**Comment by Xm4s** [comment]
Hi,

the screenshots we are addressing in this issue are the one used as a background when a user turn a page if baker is set to run in "screenshot" mode.

What you are asking is a completely different feature, that we might considering adding in a future release.
If you want you can open a specific issue about it where we can move the discussion forward.

Thank you.

**Comment by inventionarts** [comment]
Hi.

If I understood the screenshots, they were taken when the page first loaded. Does this update imply that once could run through the pages, thereby generating the screen shots, then recompile a final, shippable version wherein the screenshots are available, with no first-time render? 

Put another way, would part of the release process when using the screenshots be to generate all of them in testing?

Hope the question makes sense. Thanks.

**Comment by folletto** [comment]
The release process is going to stay as simple as it is now: the screenshots are just one of the two new rendering modes to make the reading experience more pleasurable for the users, reducing lag and the impression of slowness, working around iPad limitations. The app will take screenshot in the background in order to make the page switch smoother. ;)

Here some more details: https://github.com/Simbul/baker/wiki/Baker-rendering-modes

**Comment by inventionarts** [comment]
Thanks, yes I understood the intent and had read the rendering mode documentation. I asked because it seems related to [Issue 122](https://github.com/Simbul/baker/issues/122) re webkit animation playing out before being visible by users, and 3 card vs screenshot mode.

What I was trying to ask is if the user will inevitably experience the delay once as the screenshots are generated upon first viewing (which invalidates screenshot as a way to address 122), or if the individual page screenshots can be rendered and saved with the app prior to release so that user never experiences the delay? (Or alternatively simply allow the inclusion of a static loading image per page, pre-rendered offline by the developer, again addressing the preloading of non-looping animation problem).

**Comment by folletto** [comment]
It's in the code (commited yesterday, just create a folder called "baker-snapshots" inside the book/ folder), but it's going to be unsupported in the upcoming 3.0 release to not delay it further. Probably it's going to be in the 3.1 release after we implement it better (so yes, it's subject to change). :)

Please, open a new issue for that, so we can add to the 3.1 milestone. :)

**Comment by nruffilo** [comment]
I have a few questions about "screenshot" mode.  First off, your documentation isn't clear if I should use the param name "screenshot" or "screenshots":

"    -baker-page-screenshots (string) - since 3.1:
    Path to a folder containing the pre-rendered pages screenshots. The files must be named screenshot-portrait-1.jpg for portrait and screenshot-landscape-1.jpg for landscape, where '1' is the page number, incremental (1, 2, 3, ...).

Behaviour properties:

```
-baker-rendering (string, default: "screenshots"):
Possible options are "screenshot" and "three-cards", all lowercase. See the page on Baker rendering modes."
```

Second,

My book.json has this:
    "-baker-rendering":"screenshots",
    "-baker-page-screenshots":"page-screenshots/",

but things seem not to be working.  Do i need to have the directory "page-screenshots" in my /book directory (it is) or where should I have it?  

Thanks!

**Comment by Xm4s** [comment]
Hi nruffilo,

First of all thanks for the comment :)
You are right, there's a typo in the second line of the **-baker-rendering** property, possible values are **"screenshots"** (with the final **s**) and **"three-cards"**.
I've already fixed the related wiki pages.

About your second question, the **"-baker-page-screenshots"** is a property that let you specify a folder that contains pre-taken screenshots for your book that can be used by Baker instead of the live-generated ones.
The folder must be inside your book and the files need to respect the naming convention specified on the wiki:

> The files must be named screenshot-portrait-1.jpg for portrait and screenshot-landscape-1.jpg for landscape, where '1' is the page number, incremental (1, 2, 3, ...).

We have a guide to easily pre-generate book screenshots with Baker itself, you can find it [here](https://github.com/Simbul/baker/wiki/Take-pages-screenshots-for-a-Baker-book)

If you specify the folder Baker will use all the screenshots there, if a specific screenshot is missing Baker won't generate it. If you want Baker to handle screenshots by itself just don't set the **"-baker-page-screenshots"** property in your book.json :)
