### ISSUE TITLE
Page screenshots not clearing

### ISSUE THREAD

**Issue by swfMonkey** [Simbul/baker#185]
Running a test project in 3.0 I noticed that regardless of the book folder I use, the original screenshots of the first book build are always there. Since I used the hpub sample from the baker site (a study in scarlet) those are the snapshots that keep appearing between page loads. I tried cleaning the build file and even deleting the xcode local builds but nothing seems to work. Any help is appreciated.

Thanks!

**Comment by folletto** [comment]
That happens because Xcode doesn't clear the remote app when you do a new build.

You did correctly in cleaning the build folder and everything, the only missing step is removing as well the app on the iPad and compiling it again. 

Thanks for pointing out, we are going to make this clearer in the tutorials. :)

**Comment by swfMonkey** [comment]
Molto grazie folletto!

Deleting the app from the simulator did the trick. I've never had to since most of my other test builds are loading their resources dynamically.

Please keep up the great work you are doing here!
