### ISSUE TITLE
Screenshot render mode: making it useful by a little trick!

### ISSUE THREAD

**Issue by rocketjoe** [Simbul/baker#191]
dear baker team: great work!

I played around with the rendering modes and I really wondered about how the screenshot rendering mode works! With only a little trick you could make it really useful:
1. Why does baker take the screenshot after the page was loaded? That's wrong. You should take the screenshot when leaving the page! So you have a screenshot of the last page scrolling position. Render mode "three-cards" obviously stores that last page position. If you do the same on screenshot mode, you have a nice page-return.
2. Combine 1. with pre-stored screenshots! When the reader first swipes to a new page, the page position is alway the top position (scrolling = 0). When the content creator could provide these first screenshots for every page, one would have a swipe effect equal to render mode "three-cards" (which is ressource hungry and slows down scrolling).
3. When the user leaves a page, the old screenshot should be replaced by the current one. This should also be the mechanism to handle orientation change while swiping through the pages. The file name of the stored screenshot should have an orientation pre/post-fix. If the reader returns to a page with a already stored screenshot and the orientation pre/post-fix does not match, baker must not use this screenshot... overwriting it by leaving the page (creating the new screenshot).

**Comment by densmirnov** [comment]
I think the good idea is to make screenshots not when page is loading nor we are leaving it, but when we are compiling the application. I think this can accelerate overall application loading speed and so we can achieve very smooth transition between pages.

**Comment by Simbul** [comment]
Caching (or pre-loading) screenshots sounds like a sensible idea. In fact, it is in the roadmap already.
The downside to that approach is that the app bundle will become bigger - quite possibly more than double the size of the original book - but it's good to give developers a choice.

On the other issues I'm sure @Xm4s or @Folletto will give you a more thorough answer ;)

**Comment by folletto** [comment]
Follow issue #175 for an implementation of what you are asking. We are working on it right now. :)

However, we won't take the screenshot when leaving the page, because right now we have evidence that it's better to reset always the position of the page at the start, and that's why we are taking the screenshot before.
The fact that the page in three-cards stays where it was is a sort of side-effect, not a feature we were looking for, and it doesn't last: once you move two pages forward, you will lose the position.

We're open to more evidence if the users prefer to keep the pages at a specific height, however, it's just that at this time it doesn't seem a requirement from the data we have. :)
