### ISSUE TITLE
VIDEO autoplay fullscreen    how?

### ISSUE THREAD

**Issue by mutador** [Simbul/baker#192]
Anyone know how to put video in fullscreen with autoplay.

Thanks

http://itunes.apple.com/us/app/ohmygod00/id472971950?l=es&ls=1&mt=8

**Comment by k8fisher** [comment]
Ive just plugged in "videojs" player into laker, better control "I think" than the standard video player
Info available at: http://videojs.com/#adding-videojs

I came across it a few times in google searches for "fullscreen video" +ipad. 

Also change make the following change in the top of RootViewController.m (set value from YES to NO)

#define MEDIA_PLAYBACK_REQUIRES_USER_ACTION NO

Hope this helps

Kate

**Comment by Simbul** [comment]
Please notice that `MEDIA_PLAYBACK_REQUIRES_USER_ACTION` is no longer supported since version 3.0. Use the [manifest property](https://github.com/Simbul/baker/wiki/Book.json-Baker-extension-parameters) `-baker-media-autoplay` instead.

**Comment by folletto** [comment]
Actually in HTML5 at one point it was even excluded by the spec itself: http://stackoverflow.com/questions/1055214/is-there-a-way-to-make-html5-video-fullscreen

The problem is that a video autoplaying fullscreen will steal control from the final user. If you want to do that, I'd advise to do it by maximizing the video within the page using JavaScript, or similar solutions, but it will be quite annoying, so try looking for alternate solutions. :)
