### ISSUE TITLE
eBook/Magazine interaction ideas [guideline 2.21]

### ISSUE THREAD

**Issue by barrytallis** [Simbul/baker#230]
From the interwebs, I've seen this recently, including from TouchBooks.  "We've learned about ebook apps being rejected by Apple on account of their being "simply a book"(paragraph 2.21 in iOS Review Guidelines). If your app doesn't have unique features or exists in a market where iBookstore is well represented(usually foreign language ebook apps are fine, but it still depends), chances are it will be rejected as well. Please note that, unfortunately, we can not refund your license purchase if your app gets rejected on these grounds."

Given this, while I don't see this as an issue, can we start a dialog of what we feel are good examples of interaction, etc. that would prohibit our solutions/apps being rejected by Apple?  

Thoughts?

**Comment by inventionarts** [comment]
Barry, a good idea. 

One suggestion: browse through the various approaches that designers have taken in developing interactive, non-fiction content at NYTimes.com. Not applicable to all categories, but nonetheless may be considered a showcase of patterns and a source of inspiration (but not of outright cribbing, of course!).

http://query.nytimes.com/search/sitesearch?query=interactive&more=multimedia,past_365

**Comment by inventionarts** [comment]
One related suggestion: many such designs can be implemented without much if any hand-coding using Hype, by http://tumultco.com - and dropped pretty much directly into a book.

We've found it beneficial to do a fair amount of custom JavaScript, particularly to build "data-driven" mini-apps for the page, rather than hardwired, multi-scene Hype presentations. The good news is Hype does support such custom coding, too.

Similarly, Sencha Animator offers ways to attach behaviors to images, or to move between scenes within an animation. We have found the animations are smoother using Sencha, as they routinely optimize to take advantage of hardware acceleration, and not clear Hype does this as aggressively.

**Comment by folletto** [comment]
As far as I know, and for a few publications that had problem in the past and published here, to past through that is usually as simple as adding a few animation all over the book. In the book I saw rejected and then accepted they just added things like eyes blinking or tiny movement in some illustrations, and that was enough to pass the approval.
