### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by ghost** [Simbul/baker#249]
You always have this debate I guess - native or web. I think this is especially true now.

We are architecting a number of features into a book including users selecting themes, sharing on FB, etc.

I have considered using something like ToolDrawerView natively and integrating it on top of Baker for certain features and then it occurred to me that we can probably do all of it if we did get/sets we need with cookies. Perhaps there might be a mix of both. We're not sure.  The principle reason is to get social - ala ShareKit or something.  I know that launching FB in a browser is not a really great strategy in IOS and I'm familiar with Sharekit; however, I don't want to clutter the UI.  I may stick sharing in the lower chapter view...

I see that cookies can be persisted on app exit and retrieved with this:

http://stackoverflow.com/questions/4597763/persisting-cookies-in-an-ios-application

Might be interesting to include in the framework. Thoughts on Cookies?  And perhaps a conceptual thread violation: Thoughts on where to throw in little utilities like sharing in the app?

Thanks in advance.

**Comment by folletto** [comment]
This tip about cookies might be very interesting, we'll look into it. :)

**Comment by Simbul** [comment]
I just did some testing. They seem to confirm what [one of the answers](http://stackoverflow.com/a/8713316/551557) to the question you linked in your first post said: you shouldn't need any extra code to persist cookies.

For my test I included some very simple code in one of the html pages (after including jQuery, because I'm lazy :D):

```
<script type="text/javascript">
  $(document).ready(function(){
    alert("|" + document.cookie + "|");
    document.cookie = "ck1=session; expires=; path=/";
    document.cookie = "ck2=persistent; expires=Fri, 3 Aug 2101 20:47:11 UTC; path=/";
  });
</script>
```

As you would expect, the first time you open the page the alert is empty. If you then close the application (even going as far as removing it from the multitasking area) and reopen it, you will see that the cookie with the expire date has been persisted.

The other StackOverflow link you posted seems to be concerned with setting cookies using ObjC code, which looks like a different problem to me.

Other than that, the only issue I could find is this one: http://stackoverflow.com/questions/5837702/nshttpcookiestorage-state-not-saved-on-app-exit-any-definitive-knowledge-docume

It would be interesting to know the results of your tests on cookies, if you're willing to share them.

**Comment by Simbul** [comment]
Hi @JackWS, any news on this?

**Comment by folletto** [comment]
I quickly read your code and it seems you're not setting an expiry date for it! :)
Without expiry date, it will be killed straight off.

Have a read: http://www.quirksmode.org/js/cookies.html

**Comment by Simbul** [comment]
What do you mean by zipping?

**Comment by Simbul** [comment]
It sounds slightly unlikely that screenshots-mode will affect cookies, but let us know what you find out.
(Just to be clear: screenshot-mode makes the experience of turning pages smoother, but ultimately the HTML page is always loaded and rendered).

**Comment by Simbul** [comment]
Any news @JackWS?

**Comment by Simbul** [comment]
I'm closing this issue. Feel free to reopen if you have any more info :)
