### ISSUE TITLE
Non-Selectable Text

### ISSUE THREAD

**Issue by davethackwell** [Simbul/baker#259]
Hi guys & girls,

Is there by any chance a way of preventing users from selecting text on a page? By that I mean when a user holds their finger over some text and they get the pop-up asking to select/copy etc..

I expect that this isn't possible because of how Baker uses WebKit & HTML but I thought I may as well ask just in case...

Thanks

Dave

**Comment by mutador** [comment]
i hate this , because it happens too in images as buttoms etc....
someone knows how to desactivated this?

**Comment by folletto** [comment]
I would advise against it, because one of the values of creating HTML pages and not images or native is _exactly_ that people can copy and paste.

However, if you really, really, really want it, it's what we wrote in Issue #96: 

It should be this CSS command, put together by @usaps: 

```
body {
    margin: auto;
    -webkit-tap-highlight-color: #d3f9f2

    /* Disable selection/Copy of UIWebView */
    -webkit-touch-callout: none;
    -webkit-user-select: none;
}
```

I guess, that the best solution would be if you can apply this rule _only_ to buttons and interactive elements, keeping the ability to select and copy text intact. :)

Source:
http://stackoverflow.com/questions/923782/disable-the-text-highlighting-magnifier-on-touch-hold-on-mobile-safari-webkit

**Comment by davethackwell** [comment]
Folletto,

Thanks very much for your really quick response. I understand what you mean & for some apps I imagine that letting users copy & paste is a good thing. 

I'll give the code you said a go...

Thanks again,

Dave
