### ISSUE TITLE
Not using Newsstand?

### ISSUE THREAD

**Issue by davethackwell** [Simbul/baker#260]
Hi again,

My apologies if this is covered elsewhere but...

... is there a way of stopping the App-icon from appearing in Newsstand in the latest Baker build? While I like the fact that this feature has been added, I want my app to appear as a standalone icon on a homescreen. 

Cheers

Dave

**Comment by folletto** [comment]
Yup, just disable Newsstand here following the instructions from the wiki:
https://github.com/Simbul/baker/wiki/Newsstand-support

You just have to turn a flag off.

It's a good idea since it seems that Apple requires a full implementation of Newsstand and if you can't include it, it's better to turn it off (we are going to fix that soon). :)

**Comment by davethackwell** [comment]
Oops, I must have missed that in the Wiki!

Thanks very much,

Dave
