### ISSUE TITLE
General Performance - Loading Times

### ISSUE THREAD

**Issue by sabgottfriedx** [Simbul/baker#303]
Hi,

I am still fairly new to Baker. I actually came across it through this blog entry, which reviews all currently available opensource magazine frameworks: http://blog.imagcon.de/2011/06/magazin-frameworks-fur-das-ipad/ 

The reviewer reported the bad display performance of baker - more specifically that after each swipe over to the next page, pages need 2-3 seconds to load. Now, I did some research myself and downloaded a couple of magazines produced with Baker. I have actually experienced the same - in each magazine, pages take a couple of seconds to load. (I am using an IPad 1 with IOS 5 and I have recorded a short [demo video](http://www.youtube.com/watch?v=Ztk_6DQsd2A&feature=g-upl&context=G25e98cdAUAAAAAAAAAA) of me swiping through 4 different baker mags. )

For some reason slow performance does not show up on simulator - just in all the magazines I downloaded. And I dont have a developer account to test my own stuff yet. 

Is this slowness true to all mags produced with baker? Wanting to produce a professional mag for people used to fast performances that would renders Baker an impossible solution for us. Yet, I think that in terms of the architecture, it would still be my preferred environment to work with. 

Are you currently working on improving performance or are you planning on doing this in the future? Does the magazine framework use any sort of preload or pre-caching function?

Thanks

**Comment by folletto** [comment]
_That's a really old article there!_ :)

Baker since version 3.0 has two different modes to decrease latency:
http://bakerframework.com/log

There are two modes: screenshot and three-cards. You can read more about it here:
https://github.com/Simbul/baker/wiki/Baker-rendering-modes

By default it uses screenshots, and you can make this even faster if you provide the initial screenshots in the book itself, otherwise Baker will do it by itself.

Unfortunately, it's a limit of the software stack provided by Apple and the hardware itself. **Any** publishing framework that tries to provide the same quality and flexibility of Baker has the same problems, and they all try to address the problem with different kinds of workaround. The problem is less visible on iPad 2 and we expect to be even less on future versions. :)

The problem with the books out there is that we have no way to know which version they use: any version before 3.0 will have the loading issue, and after 3.0 the responsiveness depends if they are using three-cards or screenshot, that's why you still find books that sport the loading behaviour. And even that, some authors prefer that to other solutions.

**Comment by sabgottfriedx** [comment]
Thanks for your quick reply folletto - i am glad to find out there are work arounds.  

Has anyone out there made a magazine available that uses these rendering options? 
Would be awesome to test how this is working in real.

**Comment by folletto** [comment]
Yes, check the showcase:
http://bakerframework.com/books

I can't point directly to books made in that way, since as I said before they don't disclose the version of Baker they are using, but you should find them quite easily there. :)

**Comment by sabgottfriedx** [comment]
hmmm I downloaded 10 of those and all have this issue ...
