### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by wijeweera** [Simbul/baker#308]
Greetings.   I wonder if you can put a password to view the book. If not possible with Baker, they have any ideas? Thanks in advance.

**Comment by folletto** [comment]
What do you want to protect exactly?

**Comment by wijeweera** [comment]
is to know how to distribute books only for selected users. 
the problem is distribution. add-hoc distribution needs me to control the device, send the certificates, the annual renewal ... is intended to test it out before the sale is not for a one-person distribution.
 For simplicity I had happened to create a password for those users. and who agreed to the contents of the application identifying themselves. 
 example, a letter from a restaurant, if I want only what the company may have, as it is distributed? another example, children's stories completely custom-made paper. with some names, places, etc.. if to make an interactive book for a child only as could get on the app store by limiting the downloads? 
I read on the distribution b2b but not available in Spain and if it's not what I want. 
Maybe  it's stupid what I'm thinking, but the iphone has so many possibilities ... and Apple gives so few solutions greetings and thanks for the help.

**Comment by folletto** [comment]
Well, it's a very custom requirement you have there, and right now it's not something that Baker can do. If you don't require a separate payment (since that will be against Apple policies) you could build an app yourself that does that. It could even be that you show first a login page on Baker and then you do everything from remote on the server - authentication and such - and then you allow the download of the books. All remote.

I'm afraid we can't do much more at this time.

**Comment by wijeweera** [comment]
because I can not copy the comments to wear in the google translator??

 The reason for not wont to put the payment application in the app store Espor the subject of paperwork, taxes ... I have not had any experience with payment applications, certainly not as complicated. thanks!

**Comment by folletto** [comment]
Well, if you have no experience then it's better to use the App Store... and actually, that's almost your only choice if you release payment based apps.
