### ISSUE TITLE
Scroll down to anchor with the effect similar to dossier-headline-arrow

### ISSUE THREAD

**Issue by vladimirt2000** [Simbul/baker#311]
Hi,
I'm working in a catalog for a university and in some page I have 10 pictures of faculty members. Below each picture I have 2 buttons: Video and Full Bio. When the user clicks on video, appears a lightbox with a video.
When the user clicks on FullBio, the idea is to scroll to an anchor which is below the main content.
The problems are:
- It goes to anchor without an scroll effect
- For some reason, it works erratically. Sometimes go to anchor, sometimes do nothing

How can I have the scroll effect similar to the "dossier-headline-arrow" in a link to an anchor?
Thanks
Vladimir T

**Comment by folletto** [comment]
It's quite simple to achieve that, it should be done in javascript. There are a few libraries and examples out there. A good one is this: http://djpate.com/2009/10/07/animated-scroll-to-anchorid-function-with-jquery/

In general, if you google around with queries like "jquery scroll to anchor" or "javascript smooth scroll anchor" you'll find what you are looking for. :)

**Comment by vladimirt2000** [comment]
Ok, I'll search all possible options, thanks! But, why can't use the effect that's built-in in Laker, and works great?

**Comment by folletto** [comment]
Well of course. Use it if you prefer. :)

**Comment by vladimirt2000** [comment]
That returns to my first answer. How can I do that?

**Comment by folletto** [comment]
Uhm... wait. We are probably not understanding each other. The scroll is a simple javascript as I linked above. What are you asking exactly? Could you explain it better if it's not a simple smooth scrolling? :)

**Comment by vladimirt2000** [comment]
Davide,
I know some examples from Internet to do the smooth scrolling, using some
Javascript.
But, if that feature its working now, why I need to include new Javascript
if I can use the library that is somewhere in the Laker code.
I searched all the Laker code, and I didn't find where's the Javascript
that does the smooth scrolling for the "dossier-headline-arrow" link, or
how to do it. There's nothing in the CSS files.

Vladimir

**Comment by folletto** [comment]
Ok, now I probably got it. :)

Let's do one step back first: Laker is PURE HTML/JS/CSS, there's nothing in there that's not doable on the web. On the other side, Baker doesn't do anything inside the page itself. There's a clear split. :)

So, I guess that you are referring to... the standard vertical pagination of Baker, that happens on the edge of the screen, regardless of the book. That's managed in Baker, there's no tie at all with Laker (even less with "dossier-headline-arrow") — Florian just did a smart thing and put the arrow under Baker's active area. It's an Objective-C animation, specifically `goDownInPage` and `goUpInPage`.
An Objective-C animation that behaves like the standard JavaScripts you can find on the web. ;)

This means that you can simply use JavaScript and do it, because using Objective-C would be a bit overkill for that. :)

**Comment by vladimirt2000** [comment]
Thank you! Now I really understand how it works. I thought that was a
Javascript code that does the magic.
Of course is better to do it in Javascript and not touch Objective-C code.
Best regards.
Vladimir

On Thu, Feb 16, 2012 at 11:33 PM, Davide Casali <
reply@reply.github.com
