### ISSUE TITLE
No margins ( left & right ) in urls opened within app

### ISSUE THREAD

**Issue by Dreeke** [Simbul/baker#321]
Has anyone else found that when opening webpages through a url within the Baker app there are no left and right margins on the rendered page?

I have tested the same pages using mobile safari and they look normal. However, whenever opening a link with the baker app those same pages are without those margins.

**Comment by folletto** [comment]
It's related to the `zoomable` property of the book, `false` by default. Since it's false, and you open a page inside the book itself, what happens is that the page itself will not be zoomable, and set at its default baseline size.

What are you trying to achieve exactly? Because:
1. If it's a page that is designed to be opened inside the book, then it's better to design it properly at native resolution.
2. If it's an external page, it's probably better if you use `referrer=Baker` to open it in Safari
3. In any case, you might want to have a look at the [meta viewport property](https://developer.mozilla.org/en/Mobile/Viewport_meta_tag) that you can include in the HTML page.

I hope this helps. :)

**Comment by Dreeke** [comment]
I have resolved the issue initially by adding media-queries to the page's css file. With your input I now understand what was happening so thank you! 

This page is not a dedicated design for the book and I need to open it within the app so opening in Safari is not an option. 

( Need to add more interactivity to our book so it gets accepted into the App store - go rejected at first attempt on the grounds it should be a book in the iBooks Store ... sigh ... ).

**Comment by folletto** [comment]
You're welcome. :)

Yes, that limitation by Apple is indeed a problem. We usually suggest to add simple animations or effects, it's usually enough. :)
