### ISSUE TITLE
Content loading in index view

### ISSUE THREAD

**Issue by mikapau** [Simbul/baker#335]
Hi,

Our client happened somehow to create a situation with our ebook, in which new page was loaded in index view instead of page view. We don't have any more specific info about the situation, but we know that they used iPad 1, which is of course slower than iPad 2.

As we tried to replicate that situation, we found out that if you click very quickly a link on index view and a millisecond later (pretty much simultaneously) click on another link on page view, Baker loads both contents, one on page view and another one on index view. We got the same situation replicated with Baker 3.1 on iPad 2, see the screenshot: http://oi43.tinypic.com/mwskqv.jpg

Otherwise clients are very satisfied so many thanks for your work!

Mika Paulasaari

**Comment by folletto** [comment]
Thanks for the feedback, we'll look into it. :)

**Comment by Simbul** [comment]
I've done a bit of testing and managed to reproduce the issue.
When you tap simultaneously on a link in the index bar and on a link in the main view, the index bar loads the page the link is pointing to, instead of delegating that to the main view. The main view works as expected.

Usually the index bar disappears after this kind of interaction. In this situation, when reopening the index bar, the content will be blank. However, if we disable hiding, the index bar remains visible and shows the page that should have been loaded in the main view.

I'm still working on a fix, this is the current situation of this ticket ;)

**Comment by mikapau** [comment]
That's good that you also managed to reproduce the issue as it doesn't happen everytime. It seems very unlikely that an average user would tap two links at the same time, but that was the situation in which we got that result.

But also as we tested our book (which is already approved to Appstore) on iPad 1, one time, a link on index bar responded so slowly to a tap, that the user managed to tap the same link three times (thinking it didn't register the tap) and the same kind of situation happened - same page loaded on index bar and page view.

So, without any knowledge of how the framework really works, maybe it would be possible to make some solution which blocks other requests if the book is already loading some content, or if the user has tapped on a link. :?

**Comment by Simbul** [comment]
It should be fixed now. If you can give a spin to the latest version on master and let us know whether that fixes it for you, that would be great!

**Comment by mikapau** [comment]
Thanks a lot for a quick fix! We updated the app with the latest master version of Baker and it seems that this issue is gone now. We tested it on iPad2 and couldn't reproduce the issue any more.

**Comment by mbayona** [comment]
It seems I have the latest version of Baker, with the changes shown above, and I am getting the same error reported here.  The app starts, the index file loads, but on click a white region appears with the linked file showing in that space, instead of the navigation images...
