### ISSUE TITLE
Opening modal web view in landscape: 'Safari' button doesn't show

### ISSUE THREAD

**Issue by Dreeke** [Simbul/baker#383]
When viewing a page in landscape and opening an external link with a the modal web view the 'Safari' button in the top right doesn't appear. Rotating to portrait won't make it appear.

One needs to close the modal window first and open it while in portrait view for it to appear. It then stays in both orientations.

**Comment by Simbul** [comment]
Just tested: I can confirm the bug. We will look into it, thanks!

**Comment by Simbul** [comment]
A first quick investigation shows that the problem is the toolbar width, which is far more than 1024px. The action button is thus displayed out of the viewport.

A related issue is the size of the view and the webView in `ModalViewController`, which are 768 (instead of 1024, as should be in landscape).

This may prove to be related, so I'm pasting it here as a reminder: http://stackoverflow.com/questions/2664980/uiscreen-applicationframe-returning-incorrect-rectangle-on-landscape-application
