### ISSUE TITLE
Bakerframework 3.2 - scrolling pages issue

### ISSUE THREAD

**Issue by krisix** [Simbul/baker#397]
Hello,

I am creating a fork of your BRILLIANT Bakerframework project. The work is in progress so I didn't publish it yet.

After release of version 3.2 I've tried to upgrade files to the new version. But there are some issue with this new version when I scroll pages.

This also happens with a new empty project - I've created new project and recorded the issue. You can see that some pages are gray - not white.

http://www.screenr.com/6OM8

The same error is on the device (test with iPad 3gen).

Krzychu

**Comment by Xm4s** [comment]
Hi Krzychu!

Since we don't know what changes you may have done to the code it's kinda hard to tell if is a bug of our framework master branch. As soon as you'll publish the code, if the problem persists, we'll look into it.

I actually may have an idea of what your problem is: since in Baker 3.2 the webview background is transparent (it was necessary to fix the annoying flash page bug) maybe the gray color you see is the back of the webview.

Could you please check if the body of your pages has a background color and, if not, check if setting one solves the problem?

**Comment by krisix** [comment]
Xm4s, thx for your answer. This issue also occurs on empty Bakerframework project, but...

Setting background color solves the problem :)

What I am trying to do with my fork is to extend functionality to support multiple books/magazines. I think I need 2-3 weeks to finish project and release it on GitHub.
