### ISSUE TITLE
Req: progress bar + ToC

### ISSUE THREAD

**Issue by wesleyhodgson** [Simbul/baker#4]
A progress bar while reading the book would be super handy. I've got some ideas for styling. :)

Ditto for a Table of Contents. Perhaps by swiping down at the top of a page? Kind of like the refresh gesture in Tweetie/Twitter for iPhone.

**Comment by folletto** [comment]
. The progress bar exists, but appears only when you're scrolling. ;)

. For the ToC, I think it should be handled and styled by the book author, with hyperlinks and everything the author feels it's ok.

What do you think about this approach?

**Comment by wesleyhodgson** [comment]
- Oh! I didn't even see that down there. I assume that's just the standard webkit scroll bar thing, right? Not sure if there's a way to make it a little more obvious.
- So, you mean just having a ToC at the start of the book, and that's it? My issue is that if I'm at the back of the book and I want to get back to an article near the front, I'm swiping for 60 seconds.

**Comment by folletto** [comment]
- Yes, for now it's that. We are trying to add as less "administration debris" as possible, in order to allow book authors to be in total control of the look. It's not probably feasible completely, but we are trying. 
- Yes, the ToC is the starting point. Consider that Baker's ebooks don't have real "pages", but "chapters", so if you link the chapter to the ToC and the ToC to the chapter, you're set. That said however, I got your point, it could be annoying. Do you have any suggestion with low "admin debris"?

(after the discussion I'll split this issue in two since we are talking of two different things)

**Comment by sstarr** [comment]
How about having Baker recognise a div with the id `navigation` and have every page scroll past this when it loads, so it's effectively hidden from view until the reader drags the page down to reveal it. You could make it slightly 'sticky' so that unless you deliberately pull the page down more than a few millimetres it springs back out of view.

Actually, this could probably be done in JavaScript anyway but I'm not sure it would be possible to avoid the navigation div appearing briefly when the page loads.

**Comment by folletto** [comment]
yes, I think it's possible in JS since we have all the events to do that and the animation will make it discoverable, so not entirely bad. :)

But I agree, and the solution you just proposed could be a good point in the right direction. Are you able to make a test to see if it's possible to load an HTML avoiding the "brief flash of menu" effect? If it works, that could be a good answer. :)

**Comment by Simbul** [comment]
Eventually, I think that a TOC is something that should go into the HPub format definition.
As a quick working solution, I think the div+JS is great: it should be working already, without even requiring changes in the framework.

**Comment by sstarr** [comment]
I'll try and find some time to experiment with this over the weekend.

**Comment by sstarr** [comment]
OK, `<body onLoad="window.scroll(0,200)">` works and there's no jump when the page loads. This still feels a bit clunky to me though because if the reader scrolls down and then flicks back to the top of the page, it obviously doesn't stop scrolling until the navigation is revealed. I'm sure there must be a more elegant HTML/JS solution to the navigation issue though so I'll give it some more thought :)

**Comment by folletto** [comment]
I'll close this one for the time being, however mainly because we are talking about two different things here instead of one. :)

I'd say that:
. Progress: it's already there and for now it seems working well (» duplicate).
. ToC: it breaks the principle "the design is all inside designer's hands", so it's probably a topic we need to raise when the HPub standard is a little more formed (» delayed).

However, about the ToC there might be different opinions so in that case feel free to open another, more focused, issue. ;)
