### ISSUE TITLE
leaflet in baker publication

### ISSUE THREAD

**Issue by designomatt** [Simbul/baker#420]
Has anyone been able get leaflet (leaflet.cloudmade.com) to work in their publication? I have the HTML files working fine on their own but when I put it together in XCode the app compiles but only shows a black screen. The console shows the app is "working" but I am stumped. Any guidance is greatly appreciated.

**Comment by nin9creative** [comment]
Does any of the book work?  Or just pages where you have the maps?

**Comment by designomatt** [comment]
Yep. As a test, I just added the page to the example project updating the book.json, Book Index.html and index.html files.

**Comment by Simbul** [comment]
Why have you had to modify so many files?
To get the test to be as simple as possible, I'd try:
1. Compiling the example project with no modifications, just to make sure it is working fine
2. Replacing the code for one of the existing pages (maybe not the first one) with the Leaflet code

If this fails to give you any meaningful insights, try removing or adding the Leaflet CSS and Javascript includes one by one, until you find exactly where the issue is ;)

**Comment by designomatt** [comment]
Haven't modified any files…took the simplest sample of leaflet that works in the browser and embedded it into the sample baker publication as another page and it won't work.

**Comment by Simbul** [comment]
Yup. What I mean is: don't add any new page, just put the code in an existing one.
What's the sample you used btw?

**Comment by designomatt** [comment]
i will give it a try and see what happens (i am using the sample book project that comes with the download).

**Comment by designomatt** [comment]
Problem was the <meta> information was different on the newly added page and the existing. replaced the offending meta data and leaflet is working well.

**Comment by Simbul** [comment]
Cool!
