### ISSUE TITLE
Free Preview portion of magazine in Newsstand

### ISSUE THREAD

**Issue by pterotype** [Simbul/baker#423]
Hi all,

As we add features one-by-one to our newsstand magazine, we feel that the first one we want to add is the ability for users to download a free "preview," a portion of that magazine so they can see if they want to buy it.

I haven't uploaded the magazine to iTunes Connect yet, so I apologize if this feature is handled there, however, my question is, what is the best way to implement a free "preview" of the magazine?

**Comment by folletto** [comment]
I think you could just include the "preview" as your default book, and then use the `book://` protocol (see the wiki above) from the last page to download the full version. :)

However... the problem is going to be the payment, since you'll have to implement yourself the payment system. Otherwise, like many do, just add instead of a `book://` link a link to the full version of the book (paid) on the App Store. :)

**Comment by pterotype** [comment]
Hi Davide,

Thanks for the reply. I see how this could work, however, this seems to point to the root of one of the problems with Baker and that is the fact that it does not support In-App purchasing at this time. I do intend to release multiple issues of my magazine as time plays on, and I will require a "store-front" for my magazines and the ability to preview portions of each, and in turn, make purchases of each.

Any word on if and when Baker will support In-App purchasing?

**Comment by folletto** [comment]
Sure, but then that will require first Issue #20 that will be delivered in version 4, and on top of that the in-app purchase.

So the answer to "if" it's yes, it's Issue #20, about the "when" I can't give you a timeframe, since our resources are limited and right now we are focused on Issue #59.
