### ISSUE TITLE
Bug with Audio Files Beyond 60 mins long

### ISSUE THREAD

**Issue by freakandgeek** [Simbul/baker#424]
With audio files that are over an hour long, the countdown logic is flawed. It ignores hours.

So for instance with a file that is 1 hour 13 min and 11 seconds, it will display as 13:11 in the countdown (should be showing 1:13:11) and will not properly countdown.

**Comment by folletto** [comment]
Did you try to open the same page in Mobile Safari?

**Comment by freakandgeek** [comment]
No, but I see the bug in regular Mac Safari.

**Comment by folletto** [comment]
Then I'm afraid but there isn't much we can do. 
You should file a bug with Apple. :)
http://bugreport.apple.com/

You can maybe try to see if there's any JavaScript that could support a custom interface.

**Comment by freakandgeek** [comment]
Blame the issue on Apple? Sorry this does not compute at all. If you are going to advertise audio handling as a feature, shouldn't it work with files longer than an hour?

**Comment by folletto** [comment]
Yes, it should. :)

However the bug comes from an Apple library (probably the QuickTime component loaded in UIWebView) and it's deeply buried inside their software stack. I'd love to help and solve this issue but unfortunately we have no control at all over it.

The only chance you have is to open a bug at Apple and hope it gets solved in iOS 6: http://bugreport.apple.com/

I'm sorry.
