### ISSUE TITLE
looking inside baker app

### ISSUE THREAD

**Issue by moushik** [Simbul/baker#428]
Hi everybody, 

looking at the source code, for me, is the best way to learn, so I downloaded some publications and changed the .ipa extension to .zip. In some cases there's a "book" folder with all assets in it (images, html, etc.) but for the new issues, I found no html, only images and other assets.

I try to imagine where are all the html files and the .js files...

**Comment by folletto** [comment]
It depends a lot on the magazine itself. Some of them just download the book afterward using the `book://` protocol and others move around the book just to avoid well.. what you just did, for piracy reasons. :)

As for learning, I'd suggest you to contact a few people that produced these magazines and books, even just to ask if you can do what you described, if not asking for better insights. :)

**Comment by moushik** [comment]
Thanks, folletto, I understand...
next question: how to "obscure" the book folder inside the package?

bye!

**Comment by folletto** [comment]
You can't.
If it executes, it can be done, and that's true for anything digital (with different amounts of effort).

You can open basically every single app on the store and see how they work, disassemble them and have a look at how they do things. Mostly like it makes no sense in "obfuscating" a website, there's no need in my opinion to obfuscate a book inside a package from an encrypted store that has your name in it.

But of course, some people disagree with me, and as such, you can either make the book downloadable - so, there's no IPA to open and you take care of the protection yourself on the server - or obfuscate the code, even if I believe it's more effort than benefit.

But remember: music majors failed big time in trying to enforce that, and in the end they discovered it was better to spend money on pricing and value instead of protection. And cinema majors are in the same league right now.

**Comment by moushik** [comment]
I totally agree.

thanks!
