### ISSUE TITLE
Scrollbar & Zoom

### ISSUE THREAD

**Issue by snive** [Simbul/baker#43]
Is it possible to make the vertical scrollbar show from all the time if the pagecontent is long?

And is it possible to turn on the zoom

best regard

**Comment by folletto** [comment]
You can't make the vertical scrollbar always visible (but you can build your own scrollbar class if you want to) and you can turn on the zoom, but it's not recommended because it makes the page creation process more complex (the easiest way needs you to add specific tags in every HTML page) and it creates a less immersive reading (use JavaScript on specific items if you need to zoom).

However, this is mostly a iOS SDK question, not a Baker question. ;)
