### ISSUE TITLE
private application

### ISSUE THREAD

**Issue by bahmet** [Simbul/baker#432]
hi,
is there any way to create an app / publication and publish it to limited people (not  public). say for example i create an agenda for a 7 days seminar. how can i send it to the related people, other than getting their device id one by one and send them provision and the app. 
thanks

**Comment by folletto** [comment]
As you said, you can do Ad-Hoc provisioning. The easy way to do it is to use TestFlight, that will ease the whole id management issue:
https://testflightapp.com/

**Comment by feale** [comment]
Hi, Folleto
One question.
I have a professional account in apple dev. How can I use testflightapp.com to project in long-term if my mobileprovisions will expire in 3 months, right?
Ad-hoc provisioning is different?

**Comment by folletto** [comment]
TestFlight is primarly for testing. When you said a 7 day seminar I thought it was for their consumption during the seminar itself.

I think you need to dig into Apple's documentation to see the various kinds of offering. If you want the apps to be installed and stay you should probably use an Enterprise account. However, the best source of information here is either Apple, their developer forums or Stackexchange, we can't help much on these topics.

Otherwise, just make a public, free app that will allow then access to the seminar books behind a lock system you manage. It's probably the most flexible option if I understood what are you trying to achieve. :)
