### ISSUE TITLE
Two pages in landscape orientation?

### ISSUE THREAD

**Issue by heirenton** [Simbul/baker#446]
Hi. I am wondering that if it is possible to change the number of pages in book when viewed in landscape mode. I am trying to develop a magazine for a client, who makes their pages in indesign. I am designing the mag with high-res exported images of each page. But i want to squeeze two pages together in landscape. I can show two pages with media queries without a problem, but because of this, the number of the pages would be halved. I couldn't think of any solution. May be someone can direct me to right path... 

Thanks in advance...

**Comment by cipnt** [comment]
+1 
It would definitely be a great function to have.
This app does just that http://itunes.apple.com/gb/app/nxtbook-nxtstand/id384066971?mt=8

**Comment by heirenton** [comment]
I found a brutal solution to this. I prepare the two set of images. One set with single pages one set with double page. Then i use jquery in the last page of doubles in landscape to hijack the swipe function and disable left swipe. This is kind of a hack because empty pages would be there but user could not jump to them. You have to also build navigation according to this.

**Comment by cipnt** [comment]
I did think of alternative ways to to this in javascript but nothing would be as good as something natively build into the framework. I ended up locking the the user in landscape view so they always see two pages. 
Another solution I looked at was http://turnjs.com/ but that hold all pages in one html which would make the swipe dunctionality of Baker useless. 
I think the example given in my previous post would be the best way to implement this and it needs to be done in Baker.
Unfortunately objective-c is just not my thing and can't help with this in any way

**Comment by folletto** [comment]
Hello! :)

We discussed this at lengths, and the conclusion is that we don't think we are going to develop this feature. I'm sorry if this disappoints you.

There are multiple reasons for this:
1. Users expect to have pages containing the same amount of content for consistency. If you start shuffling these around they will get disoriented, since it's an unexpected result.
2. Switching to horizontal doesn't create a page big enough to fit two pages — 2p x 768px = 1536px vs 1024px — missing more than 30% of the required space, so re-formatting will still be necessary and a single page will have to fit in 384px, an incredibly narrow column.
3. Practically no publication system supports content switching. On Adobe Digital Publishing (InDesign) you can create different content on different orientations, but it's not by design.
4. Even Kindle/iBooks when switched just re-format the same page in two columns, however being a reflowing media it's not exactly 1:1, and as such epub is pretty famous to have problems in identifying specific pages in the publication.

Also, the book you link above is simply a PDF reader that adds padding when the two pages are side by side, reducing the size of the page by more than 30% (as above) and making them incredibly troublesome for the final user.

I'm sorry.

However, I have also to highlight the fact that this approach is beneficial to the reader: creating the content to be a match 1:1 portrait:landscape is a better experience, and you can reformat the content to enhance readability and visual effectiveness.
