### ISSUE TITLE
Optimization: Page is current page and current page IS delaying loading --> load page

### ISSUE THREAD

**Issue by estim8d** [Simbul/baker#451]
Great work guys!

I have a pretty simple magazine with pre-rendered screenshots, that has full screen/big images in (base and retina) html. I get a 5 second delay on switching pages and see this in the console.

> Page is current page and current page IS delaying loading

Any tips to optimizing that speed?

Thanks - Dave

**Comment by folletto** [comment]
That line is necessary to make the whole thing work. :)

In the code, that's associated with the following comment:

```
// This delay is required in order to avoid stuttering when the animation runs.
// The animation lasts 0.5 seconds: so we start loading after that.
```

That's why we "delay" loading: otherwise the animation and the loading will interfere with each other.

The delay you are experiencing unfortunately it's entirely dependent from the `UIWebView` implementation speed, and we can't do much about it.
