### ISSUE TITLE
Newsstand vs app

### ISSUE THREAD

**Issue by itgiawa** [Simbul/baker#458]
I want to publish a free magazine with content that updates daily using baker. 

My concern is that the app will be rejected for being too much like a book if I submit as an app. 
But I read that newsstand is very exclusive and requires a paid subscription. I want my magazine to be free.

These guys claim you can do a free newsstand app: http://support.magplus.com/entries/21043371-guide-build-a-newsstand-app-with-only-free-issues

Does anyone have any experience with this? What do you recommend?

**Comment by folletto** [comment]
Well, first of all I think a clarification is due: Newsstand apps are exactly like other apps. So:
1. Being "free" is an option for both a standalone app and a Newsstand app.
2. Both are subject to validation
3. Newsstand apps have additional requirements: they need to support multiple issues and background downloading.

This also means that anything that "could be a book" will be rejected, regardless of being an app or a Newsstand app.

However, Baker right now (version 3.x) doesn't support multiple issues and as such you can't use it in Newsstand (nor update it daily, since every updated needs to be validated by Apple). The upcoming version 4 will be instead able to support multiple issues.

I hope this clarifies things up. :)

**Comment by itgiawa** [comment]
Thanks for the response.

I thought that if it were a newstand app then Apple would be less likely to make the "its a book" argument since issues are being downloaded and books don't download issues. If no one has released a Baker newstand app then I guess no one knows if it helps or not?

Thats great that baker will support issues. In the mean time I don't think it would be that hard for me to add downloading functionality to my own Baker app. 

I was planning on downloading new content from my server everyday, then instead of baker loading content from the book directory it would just load the content that I downloaded. 

What do you mean when you say that every update needs to be validated by Apple? Since I'm not actually changing app versions to update the content I don't think that Apple would need to validate these daily updates right?

**Comment by itgiawa** [comment]
Also, if you want help with updating issues, I wouldn't mind contributing to the project.

**Comment by folletto** [comment]
Downloading functionality is already there: it just replaces the book tho, and it's not currently compatible with Newsstand. But you can start from looking at that code, the hooks are there. :)

~

Validating: I was referring to the fact that today people that want to release new issue just submit an app update, and as such it requires to be validated. You're right: if you build the update in the app (using JavaScript) then you don't need to re-submit it. :)

~

We appreciate contributions _a lot_, they are much needed. If you want to help, just pick up a task and coordinate with us. Just avoid to do too much work at once and it should be fine (it's hard and time consuming to review loads of changes, while smaller ones are easily pulled in). :)
