### ISSUE TITLE
Blank Screen in 1.1

### ISSUE THREAD

**Issue by frantovar** [Simbul/baker#47]
Hello,

I'm having problems with version 1.1, I renamed my html files and it worked for a while but now in the simulator, when I load the application I get only a blank screen.

Any ideas?

**Comment by Xm4s** [comment]
Very strange.

Have you try deleting the app from the simulator and then installing it again? Sometimes the simulator fail to recognize correctly that some files have changed in the book directory, a fresh installation should do the trick.

If you continue to have problems post here the steps necessary to trigger the bug and we will look into it as soon as possible :)

**Comment by frantovar** [comment]
- Added book to version 1.1
- Rename project- Change "Organization Name "
- Testing App --> ALL OK
- Added icons to the folder
- Modify .plist to set image icon
- Testing App --> ALL OK
- Modify .plist to remove the icon effect
- Testing App --> ALL OK
  I explain step by step how the error occurred, thanks
- Added two files to the project for the language: "InfoPlist.strings"  and "Localizable.strings"
- Locate the two files
- Testing App --> ALL OK
- Modify .plist and added "LSHasLocalizedDisplayName" = YES
- Testing App --> ALL OK
- Locate the folder book in two languages "en" and "es"
- I try to see if the contents change depending on the language.
- Testing App --> The changes in the language "are" not visible
- Clean the targets "Build / Clean All Targets"
- Clean the cache "xCode / Empty caches ... "
- Testing App -> White Screen- Reset baseline simulator
- Testing App -> White Screen

**Comment by frantovar** [comment]
Later...
- Remove localization of "Book" folder
- Testing app --> ALL OK

**Comment by Xm4s** [comment]
Could you explain better that - Locate the folder book in two languages "en" and "es" -?
If you are saying that you have added two folder, "en" and "es", within the book directory, we have found the problem: Baker looks for HTML files only in the book directory and not in its subfolders, so maybe you see a white screen because the framework found no pages to show.

**Comment by frantovar** [comment]
Hi, thanks for your response.

What I do is locate the folder in Xcode Book "Book / info button / Make file localizable. "
-Automatically creates two folders called "en.lproj" and  "en.lproj" with a subfolder "book" inside of both.
- The program knows where to locate this folder "book" on the language that is set on your device - i don't have problems doing so in version 1.0- and thus the application is translated into two languages.

You're right, the problem is that the application can not find the folder "book. " I will review the localization process.

Keep you informed

**Comment by frantovar** [comment]
I'm reviewing the process and I do like to in version 1.0 but not working. The application can not find the folder "Book" localized trough xCode

It could be something different in the project settings?

Thanks ;)

**Comment by Xm4s** [comment]
Maybe the problem is in the way we retrive the path to the bundle book directory.

Try to change this line (132 in RootViewController.m):
"self.bundleBookPath = [[[NSBundle mainBundle] bundlePath] stringByAppendingPathComponent:@"book"];"

with this one:
"self.bundleBookPath = [[NSBundle mainBundle] pathForResource:@"book" ofType:nil];"

Those methods return the same path in general condition, but the latter should automatically recognize the localized bundle.

**Comment by frantovar** [comment]
Works! you're the best! You saved my week!!

**Comment by Xm4s** [comment]
I'm glad I could help you, hope to see your book on the app store soon :)

Thank you for pointing out this inconvenient (and also test the possible solution), that in the end led to a improvement for the framework.
