### ISSUE TITLE
CSS confusion between multiple books

### ISSUE THREAD

**Issue by danupoyner** [Simbul/baker#474]
I am using the default book as a chooser page to select either Issue 1 or Issue 2 of a magazine, using the book:// download protocol.

If I open one book, close it, then open the other one, the CSS styling from the first book carries over and is displayed in the second one - so I see the second book's content with the first book's styling. It's very confusing.

I am using Laker and the two books have the same file structure and some files have the same names, including styles.css and its imports. I'm guessing this has something to do with it, but I'd like to understand exactly what is happening before I start making big changes.

I'm using latest version of Baker from master.

Hope this makes sense!

**Comment by folletto** [comment]
That's weird... the two instances should be separated... are you able to produce a proof of concept so we can test the bug?

Also, does it happen also on the 3.2?

**Comment by danupoyner** [comment]
Sure, if you sign up on my Testflight you can download my current build and see it in action http://tflig.ht/PYio7Q

**Comment by danupoyner** [comment]
And yes, same behaviour in 3.2. It's like it holds the stylesheets in memory between books...

**Comment by folletto** [comment]
Uhm... We probably need the books to debug it. Are you able to provide an example that can reproduce the bug without sending us your work?

**Comment by danupoyner** [comment]
Probably! Pardon my ignorance, but how would you like me to do that? :)

**Comment by folletto** [comment]
Uhm basically if you can send us a small book made of just one page with fake content and css that you verified it can trigger the problem. A quick way might be to remove all the pages from your book but one, cut some part of the page, replace the text with dummy one and cut the css to just a few rules in order to see the problem.

**Comment by danupoyner** [comment]
Ok I'll do that tomorrow - just gone past midnight here!

**Comment by folletto** [comment]
It's ok. Thanks! :)

**Comment by folletto** [comment]
I think you hit yet another issue of `UIWebView`: it has aggressive caching.
See this issue:
http://stackoverflow.com/questions/3549508/prevent-caching-of-css-files-in-uiwebview-loaded-from-disk

We are not 100% sure, but if that's the case, the workaround to the problem is to add "something different" at the end of the css file you are loading between the two books, so you can have the same filename but to `UIWebView` it will look a different file. For example: `src="style.css?book=1"` and `src="style.css?book=2"`.

**Comment by Simbul** [comment]
Also, @danupoyner, while investigating this issue we ran into a bug that prevented the default book from being loaded when closing a downloaded book.
Have you discovered (and fixed) the same bug, by any chance? I'm a bit puzzled, as I can't imagine how you could have even loaded the second book, given that.

We have fixed it in c113173, have a look in case that rings a bell - I'm very curious to know ;)

And, just to be clear, this has nothing to do with resolving this issue - just an aside.

**Comment by danupoyner** [comment]
Ok, that makes sense. I have been having a bit of a play and made the link calls 'different' as discussed. So far that seems to have exacerbated the problem, but at least I know that means it's having some effect. I think I will try reorganising the file structure instead and let you know how that goes.

@Simbul I've not encountered the bug you mention - what do you mean when you say 'prevented' from loading the default book? I've had no crashes or errors when doing that. The only issue is when you use the book://local link from the popup index.html drawer - if you do that, the drawer persists over the top of the default book and you can't get rid of it (at least in the case of Laker).

**Comment by folletto** [comment]
Btw, the problem should disappear when we'll deliver the shelf branch, but we can't give you an ETA on that.

**Comment by danupoyner** [comment]
I figured! New magazine issues are every 2-3 months for me so I'll have fingers crossed the shelf will be ready for next time! Meanwhile I'll muddle through with this :)

**Comment by danupoyner** [comment]
I managed to squash the bug, I think, but in the end I resorted to completely changing my file hierarchy so there are no duplicate filenames between issues. It's the only way I've been able to reliably stop the caching from interfering.

**Comment by folletto** [comment]
That's a shame. As said, it should be solved with the version we are working on, but for now I can just say that I'm sorry a different fix wasn't available. :/

**Comment by simondelacourt** [comment]
This problem seems to be a lot alike mine, how is the caching issue going?

**Comment by folletto** [comment]
@simondelacourt not likely. I already answered on your issue, check that. ;)

**Comment by folletto** [comment]
I'm closing this issue because the branch `shelf` will automatically solve it once become the `master` branch and gets released. This means that once Baker 4.0 is released, it will work without problems. 

Track the development of Baker 4.0 by using the Milestones feature on GitHub here: https://github.com/Simbul/baker/issues?milestone=8&state=open

Thanks! :)
