### ISSUE TITLE
Glossary 

### ISSUE THREAD

**Issue by cptobj** [Simbul/baker#480]
Would like to suggest something like an internal glossary. So the publisher can specify his own glossary of terms for each publication.
Maybe something in the HPub.
In the frontend, the glossary words appears with a different typeset and can be touched so the user can see a popup with the term definition. Something like ibooks dictionary...

**Comment by folletto** [comment]
I think this should be a book-related function, defined by the book or magazine author and tailored to the specific needs of the publication. I think it could be a simple JavaScript and HTML solution: the JS loaded in each page, parsing the content and highlighting with CSS the terms it find adding a link to the specific glossary HTML in the book.

For example you could implement it with something like this JS: http://johannburkard.de/blog/programming/javascript/highlight-javascript-text-higlighting-jquery-plugin.html

We'll be glad to add this as an extension for the books, but it's not going to be part of the Baker framework, since it's pure HTML/CSS. :)
