### ISSUE TITLE
How should I remove/hide the scrollbar?

### ISSUE THREAD

**Issue by Rpadao09** [Simbul/baker#485]
I want re remove or just hide the scrollbar if its start to swipe, how can I do that? lease help me because this is just my problem in using this framework

**Comment by folletto** [comment]
It's quite a standard feature, and there's no official way to disable that since it's a very important feature for the final user.
However, if you really want you should probably look where the `UIWebView` is created and change it following the informations you can find on the web:
http://stackoverflow.com/questions/849225/iphone-is-it-possible-to-hide-native-scrollbar-in-uiwebview

Mind however that's not a public API, and as such can easily break when upgrades come by.
