### ISSUE TITLE
Jquery

### ISSUE THREAD

**Issue by DaveLEWIS** [Simbul/baker#490]
Nube Question:

Hi, I am new to baker.

Please may I ask, can JavaScript and/or Jquery be used for Baker ?

More over, which is best used for small animations in Baker interactive books.

This is a great community. Thank you in advance :D

DaveLEWIS

**Comment by cipnt** [comment]
jQuery or javascript animation will work fine.
If possible, use CSS animation because it's hardware accelerated and will look much smoother.
Whatever you can do in mobile Safari you should be able to do in Baker

**Comment by DaveLEWIS** [comment]
Hi cipnt,

I didn't realise that animation could be achieved with CSS alone.

The animation would be a maximum of five frames, bitmap images.

May I ask, is there a useful tutorial or resource to learn CSS Animation please ?

Does CSS animation work alone without JavaScript or Jquery involved ?

DaveLEWIS

**Comment by cipnt** [comment]
It really depending on what you're trying to do
http://www.w3schools.com/css3/css3_animations.asp

**Comment by bewildergeist** [comment]
Apple has some [good documentation on CSS animation (transitions and keyframes)](https://developer.apple.com/library/safari/#documentation/InternetWeb/Conceptual/SafariVisualEffectsProgGuide/AnimatingCSSTransitions/AnimatingCSSTransitions.html#//apple_ref/doc/uid/TP40008032-CH13-SW8) on their Developer website.

Also, if you end up needing Javascript after all, [Zepto.js](http://zeptojs.com/) is a jQuery API-compatible (i.e. is uses the same syntax) library that is much smaller than jQuery because it doesn't support Internet Explorer and other older/inferior browsers.

**Comment by Simbul** [comment]
Closing as inactive (and quite possibly solved by now).
