### ISSUE TITLE
Request: Rails style partials

### ISSUE THREAD

**Issue by sstarr** [Simbul/baker#5]
Are partials something you've considered already?

(and is there any way I can apply a label to an issue?)

**Comment by folletto** [comment]
Thanks for the suggestion, but at this time we don't think that Baker should support any pre-processing of the ebook because we think it's outside the objectives of a book engine.

In more detail, I can add:
- A pre-processor will add computing weight without a real added value for the user (it's a task that should be done before the publishing of the book).
- You can use or build an HTML pre-processor to create the required HTML files (up to the extreme probably of building a barebones Rails app to generate those HTMLs :D).
- HTML5 supports the <iframe> tag, and that's the proper HTML way of doing partials, even if I agree that's not the same thing, that's probably close enough if you badly need partials but you can't for some reason pre-process them.

That said I hope it's clear enough the reasoning behind this choice. ;)
