### ISSUE TITLE
Page spinner not appearing anymore

### ISSUE THREAD

**Issue by andreacampi** [Simbul/baker#50]
Just updated to master (34ba5fdc32dba1170ce7) and I cannot see the spinner anymore.

**Comment by Xm4s** [comment]
I've tried to block the webview from loading the content to check if the spinner for each page was there and... well, they are all there :)

Maybe you don't see them because the webview load and show the pages content too quick for the spinners to fully appear (a transition from alpha 0 to 1 in one second, starting from the moment the load command is called on the webview). On the simulator I have problems to see them too.

**Comment by andreacampi** [comment]
Fair enough, I didn't try that :) sorry about the false alarm.
