### ISSUE TITLE
zoom problem

### ISSUE THREAD

**Issue by hitchio** [Simbul/baker#502]
hello!
if i set  - "zoomable": true, - i´m able to zoom on doubleclick. but this also opens index, too.
so everytime i want to call the index, my page also is zooming the same time.
how do i prevent this issue?

thanx for help.
h

**Comment by hitchio** [comment]
problem not solved - sorry

**Comment by folletto** [comment]
There's no solution unfortunately, because we need to trigger the index in some way and the best way right now is on double tap. Unfortunately the two gestures overlap.

That's one of the reasons why we suggest to avoid zooming, usually it's not needed. :)

**Comment by hitchio** [comment]
you´re right - that´s just fun.

**Comment by cipnt** [comment]
How about some extra settings in the json file that will allow you to set what triggers the index(contents page):
- double-tap as it is now
- swipe from the edge of the screen, same way we open notification area, only from the bottom of the page (I've seen this in an app, can't remember which)
- some javascript function so that the user can place a custom button/graphic/link on each page to toggle the index

Also, having a setting that will allow or disable the double tap to zoom might be useful for some people, but I believe is the 'natural' behaviour if you enable the book to be zoomable

**Comment by folletto** [comment]
In general terms, the reason is simple: consistency. We don't want to introduce big alternative behaviours from the ones that are already common in other apps (where the index is either shown with one or two taps).

That said, we have Issue #350 planned to allow the third option you just quoted. ;)
