### ISSUE TITLE
Page flip effect

### ISSUE THREAD

**Issue by designomatt** [Simbul/baker#503]
Just saw this article in .net and was thought it might be useful as a discussion point for introducing a page turning effect in Baker.

http://www.netmagazine.com/tutorials/create-page-flip-effect-html5-canvas

**Comment by folletto** [comment]
Unfortunately it's not doable, because if you notice in that example the entire book is contained in a single HTML page. That's how you do that in HTML.

If you do that way, you have to do the entire book in HTML - in a single, self contained HTML. It means that you aren't using Baker and as such losing all the speed advantages of Baker over HTML (plus you will have to rewrite all the features of Baker in HTML).
