### ISSUE TITLE
Universal support in Shelf (iPhone support)

### ISSUE THREAD

**Issue by f3r3nc** [Simbul/baker#519]
The shelf HEAD as of writing (f147176a024a4dcd1074074bfd719e54b93857f3) doesn't support iPhone screens:
1. Download Button doesn't work on iPhone
2. Not optimized for iPhone screen.

It seems that 1. can be fixed by changing the width of the created AQGridViewCell to 318px.
(IssueViewController.m:74, ShelfViewController.m:160,173)

The bug is due to how AQGrid is handling the cells. (Probably an AQGrid bug).

AQGridViewData's fixDesiredCellSizeForWidth method is called at some point where the Cell's _actuallSize.width can go inf due to a division by zero (probably if the with is bigger than the with available). Interestingly, this won't affect the rectangle drown but only the touch handling.

Although, setting the size 318 will work for iPhone, it's not a solution because it's still aligned right and  the iPad version will be broken.

What should be the right fix for this?
Many of the values are hard wired.
Did you think of using nibs?
The images files under the img folder should also follow iOS file naming convention ie: ~ipad, @2x~ipad for iPad files.

**Comment by folletto** [comment]
Thanks for the feedback. We'll use this to keep track on the iPhone development side of issue #20. Right now we weren't working on that since we are still working on basic features.

We had to ditch nibs because they made things more complicated when developing more than one year ago, but everything else is correct. We will switch the hardcoded values with evaluated sizes. If you want to prepare a fix and make a pull request that would be great. ;)

Using the name convention for the images is definitely something we will have to do, since it should be already supported by `UIImage`.

**Comment by Simbul** [comment]
Fixed in d92f5d440c018e5a256ebe34d569de38b3281906.
