### ISSUE TITLE
Using "Method A Three-Cards View"

### ISSUE THREAD

**Issue by Paratel** [Simbul/baker#53]
Hello,

I'm having some issues when i try to implement the "Method A Three-Cards View"
when i remove the comment marks from the code to use "Method A Three-Cards View" i get an error 'pageNumber' undeclared, so i tried -(void)gotoPage:(int)pageNumber instead of (void)gotoPage. It builds but i if i swipe the application crashes. How can i Uses the "Method A Three-Cards View" in the latest release ?

Kind Regards,
Bart

**Comment by folletto** [comment]
You are having problem because it's a leftover from the first Baker implementation before 1.0 release. It's not supported but to the inability to the current iPad hardware to handle it correctly. :)

You might try to reimplement it if you have small pages with not much content, but start from scratch, any leftover in the code isn't working anymore.
