### ISSUE TITLE
Skewed Info Display

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#546]
I can't seem to replicate this right now or know how it happens, however it has happened a couple times in both the simulator and the device for iPad where if you rotate the screen, the info labels look like they are painted over each other with garbage.

I did get a screenshot from my iPhone.  This is basically using out of the box master code with some background image changes etc.

![iPhone](http://www.bakershelf.com/screenshots/iPhoneScreenshotMessedUp.png)

**Comment by folletto** [comment]
It happened once on iPhone to us as well, but we weren't able to replicate it, and it didn't happen on iPad for us. From what we gathered:
1. It seems to happen only when there are more elements than the ones fitting on screen.
2. It happend without rotating it, but it might be helpful to nail it down.

We think it could be a de-allocation issue somewhere, but we have not clue for now, because as you've seen it's difficult to replicate and happened only once to us on a non-Xcode attached instance.

**Comment by nin9creative** [comment]
Ok will see if I can look into it a bit...

Warm Regards,
Andrew

**Comment by nin9creative** [comment]
I can replicated it at will on my iphone 5, it looks like it renders the on screen ones fine the first time, but as soon as you scroll it overwrites them with new cells.

**Comment by Xm4s** [comment]
Thanks for the hint nin9creative, it turned out to be a simple overlapping of issue views inside the same shelf cell. Empty the cell content before adding the issue view seems to solve the problem.

**Comment by nin9creative** [comment]
Cool, glad you found it!

Andrew
