### ISSUE TITLE
Issue Data Refresh

### ISSUE THREAD

**Issue by nin9creative** [Simbul/baker#547]
It doesn't seem that hitting the refresh icon refreshes any of the metadata about the issues that are already displayed on the device (not necessarily those that are downloaded).

Should it?  What if someone wants to update the title or info display for an issue, or change a cover or update the location that the .hpub resides.  If the app caches the data then the end developer can't make those changes.

Unless I'm missing something?

**Comment by Simbul** [comment]
At the moment that't the expected behaviour: refresh is essentially a facility for checking whether new issues are available.

I agree that refreshing all metadata would be a nice-to-have, so I've marked this as a feature request. It probably won't be in 4.0, unless we find some time to sneak it in ;)
