### ISSUE TITLE
Horizontal Swiping: Remove Multiple-Page Shuffle?

### ISSUE THREAD

**Issue by thejtate** [Simbul/baker#554]
I was curious if there was any way to remove the page shuffle transition when going from a page far apart from another page. (such as clicking from Part1-01 to Part3-06)

Also, I really dig the the recent Baker update. Just fixing to dive into Newsstand publication and it really made things super easy. 

Thanks!

**Comment by folletto** [comment]
Sorry for the lack of follow up, however that animation is by design to give the user a sense of the direction where the publication is jumping, so there's no way to remove it. You could probably try to disable it by coding a different way to jump, tho.

I hope that the next Baker update will be even better for you! :)

**Comment by thejtate** [comment]
Ok, I was just curious. Thanks!

**Comment by folletto** [comment]
You're welcome! :)
