### ISSUE TITLE
Creating free subscription for Newsstand

### ISSUE THREAD

**Issue by Ajguy** [Simbul/baker#563]
I'm a little confused on something. We're preparing the first issue for our upcoming magazine, and I'm trying to work with the Baker 4.0 codebase, as we really want Newsstand support. I'm following the tutorial for Newsstand.

https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand

It talks about going to iTunes Connect and setting up a subscription, but I don't know how to find this. Does a first version of the app have to exist before such settings can be created? How does one go about this when creating a brand new app?

**Comment by folletto** [comment]
Hi @Ajguy thanks for your comment. :)

Setting up iTunes Connect is something that must be done always before any release, so you just setup the application as you would normally and you follow Apple's instructions on how to setup a Free Subscription. We can't help much on Apple's side because the documentation changes pretty much at every release and you can get plenty of support on the official forums as well. :)

I hope this helps. :)

**Comment by Simbul** [comment]
Closing as inactive.
