### ISSUE TITLE
Zoom 

### ISSUE THREAD

**Issue by molorago** [Simbul/baker#589]
Hola, hay una aplicación desarrollada con baker que se llama universo relogio, y esta al doble tap sale el carrusel y con los dedos permite hacer zoom
Por defecto el zoom no viene activado, quisiera que me ayudaran no se como activarlo.
GRACIAS

**Comment by folletto** [comment]
Could you please type in english? :)

However, if I understood correctly from my poor spanish, you are asking how to enable zoom.

It's something we **don't** advise, because makes a worse experience for the user and it's usually better to find a better design if you are in a situation where you think of using zoom.

But if you really want to enable it, just check the Hpub 1.0 specification in the wiki above. :)

**Comment by tstegart** [comment]
¿Está buscando para hacer zoom activo? Se activa en el archivo bajo book.json "zoomable": false,

**Comment by molorago** [comment]
le pongo true???

**Comment by molorago** [comment]
there is some way to enable the zoom with two fingers but not with double tap?

**Comment by molorago** [comment]
for my application is necessary to enable zoom, because is for iphone to, but no with doubletap, i want to implement zoom with scale with two fingers, there is a way to do it? or maybe a plugin that can help me?

**Comment by tstegart** [comment]
I think this is set in the HTML as well. Check the HTML code for each page to make sure it allows zooming.

**Comment by molorago** [comment]
i find this 
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=no;" />
so i have to chance the maximun scale???
But how can i disable the zoom in with dpuble tap, i only wanted with the event of two fingers

**Comment by molorago** [comment]
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=no;" />

**Comment by molorago** [comment]
meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=no;

**Comment by molorago** [comment]
doesnt work, please help

**Comment by molorago** [comment]
@folletto I do this that i found in other issue We landed a constant in master branch to turn zoom on.
It's still NOT recommended, but it's there. Also it require a change in the HTML head element of each page.

As an author, you can. Please, use it only if you are absolutely sure. ;)
BUT IT DOESNT WORK, PLEASE HELPS ME, HOW I ENABLE ZOOM

**Comment by folletto** [comment]
If you add that line in the HTML you _disable_ zoom (since it set min scale, max scale as the same and user-scalable disabled).

The only think you have to do, as I said, is to add the `zoomable: true` parameter in your `book.json`.
But please, try to avoid it changing the way you are building the magazine. It's really a bad experience for the reader.

**Comment by molorago** [comment]
i do that but still doesnt work... i understand what you say.... but is the client who want like that
why doesnt work?

**Comment by folletto** [comment]
I'm afraid there isn't much else I can say then without having the book... that's the parameter.

Uhm... Did you remove that line above from the HTML?

**Comment by molorago** [comment]
no i dont remove anything
I change in the json zoomable to true
and in the head of each html i change this maximum-scale=1.0; user-scalable=no to this maximum-scale=3.0; user-scalable=yes

**Comment by molorago** [comment]
i did something wrong?

**Comment by aspek** [comment]
Just set your  maximum scale. And remove "user-scalable=no"

example
meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=2.0;

**Comment by molorago** [comment]
Thank uu so muchhhhhhhhhh
Its work
