### ISSUE TITLE
UI Newstand Icon

### ISSUE THREAD

**Issue by UNDRRPBLC** [Simbul/baker#603]

**Comment by folletto** [comment]
The Newsstand icon will be taken from the cover of the last publication downloaded in Newsstand (so, from `shelf.json`). What exactly doesn't seem to work? :)

**Comment by UNDRRPBLC** [comment]
Yep, I'm just not getting anything showing up using showing using the simulator... Is it working besides? Also, I've disabled the SHELF_NAVIGATION_TITLE by editing line 96 from the ShelfViewController.m, is there any way to adjust the remaining button's text (BACK) to that of my liking? I've looked through and through and can't seem to find that specified anywhere. Or if not, where can the existing drop shadow color size etc. be found?
Thanks,
Joey

**Comment by folletto** [comment]
The management of the back button is completely automated by the UI code, it uses the title you removed to generate it. If you want to customize it you should re-write that part of the code, but I don't know the extent of the rewrite since it's automated code (see the documentation of `self.navigationController`).

Same applies to the shadow/color/etc. These are builtin buttons, native, so if you want to customize them you have to write the code yourself.

**Comment by UNDRRPBLC** [comment]
Cool.
Thanks.
