### ISSUE TITLE
Back end question.....dedicated server or virtual server

### ISSUE THREAD

**Issue by teckmonkey** [Simbul/baker#605]
I'm wondering what way to go..not sure of traffic requirements....

**Comment by folletto** [comment]
I'll leave others to answer with their numbers, but I guess it's difficult to evaluate, depends a lot on the size of your publications and he number of subscribers...

**Comment by nin9creative** [comment]
If you are talking about just issue hosting / issue list hosting you should make sure that you aren't violating any of the terms of service
for "web hosts".  Most have policies against using their storage and bandwidth to serve up files to something other than a hosted website.
It would suck to publish your magazine and then have your hosting cancelled because you broke the TOS.

I've talked to people that are successfully using Amazon S3.  However it can get costly with bandwidth if your app is popular.

Also check out the cloud offerings by 100tb.com.  I'm using them now and have already gone through the process of clearing with them that
hosting files for distribution by an iPad app is ok.

Andrew

**Comment by teckmonkey** [comment]
I was looking at a dedicated server...and yes push a new issue daily...like a news paper 

Tim

**Comment by nin9creative** [comment]
If you are looking at a dedicated server then I would check out 100TB.com

Their dedicated servers offer 100 TB of unmetered fast bandwidth.  For the price, it's a great
deal.

Andrew

**Comment by teckmonkey** [comment]
I saw that..everyone else is..well not a good value...virtual through go gaddy 3000 gb 99 dollars...seriously

**Comment by nin9creative** [comment]
Ok, just making a suggestion.  There is a major difference between the two.  Just FYI.

**Comment by teckmonkey** [comment]
Oh no...your suggestion...def looking into...I'd rather par more for the bandwidth...I'm just trying to wrap my noodle around how to do what I want....the back end is where I'm at...so push new issue out from a dedicated server...daily...with push notifications,,and in app subscription...lol ya that's ll

Tim

**Comment by nin9creative** [comment]
I also use WiredTree.com for a VPS that I use.  Worth checking them out as well.  Their customer service is superb.

**Comment by Simbul** [comment]
Closing this as it has gone stale.
