### ISSUE TITLE
Want my app to update daily, no need for back issues...possible!?

### ISSUE THREAD

**Issue by teckmonkey** [Simbul/baker#606]

**Comment by folletto** [comment]
Well, you could release a magazine each day, but... you should add more details about what you're trying to do, because a daily update doesn't seem like a good use of a magazine structure, unless of course you're able to release a new issue every day (like a newspaper).

Possible... it's possible: just create a Newsstand publication and update the `shelf.json` daily with the new issue.

**Comment by teckmonkey** [comment]
Exactly..I want to be able to publish daily..

**Comment by folletto** [comment]
Then, as I said. Just update `shelf.json` daily with the new issue. :)
