### ISSUE TITLE
ziping files for upload server, vps,, how?

### ISSUE THREAD

**Issue by teckmonkey** [Simbul/baker#624]
okay so help me wrap my noodle around this all okay,,, so create in html,, like iWeb,, zip files and upload them to,, (server, vps? ) so they can then be pushed out to users.....

back end,,, magrocket,, upload control panel to php,, 

so dedicated server,, or how is this acomplished exactly

**Comment by nin9creative** [comment]
The hpub that you create for the Baker viewer needs to be uploaded somewhere so that Baker can download it.  Currently in Baker, you designate the URL in the .json issue list to where the hpub is located.  When someone clicks download, Baker pulls it down.

If using MagRocket, it's the same thing except that you are using the Admin console to define your publication/issues.  However there still is a field for the hpub content url - which needs to exist somewhere available for the shelf to download it.  The only difference for MagRocket is that you are pointing to a REST API url instead of the issues.json file....

**Comment by teckmonkey** [comment]
got it,,, so basically magrocket takes the place of that json file,,, but the zips,, get uploaded to server,, or vps for call to download ,, am i right

**Comment by nin9creative** [comment]
At this point MagRocket takes the place of the IssueList json file, also reacts to the Subscription Pingback.  That is correct.  

However this discussion might be better suited on the MagRocket repo as to not muddy up the Baker guy's stuff :)

**Comment by teckmonkey** [comment]
agreed,, ill switch over,,, just wrapping my head around this,,, i just rented my own dedicated server,,, so I'm figuring it out

**Comment by nin9creative** [comment]
However if you have Baker viewer related questions (like how to make a hpub etc) that makes sense here.

**Comment by folletto** [comment]
I'm closing this issue since the discussion seems ended. Reopen if needed. :)
