### ISSUE TITLE
Performance tips regarding books

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#625]
Hello,

There are many articles on how to make websites faster.

What tips can we apply for a book in Baker.

Load of linked files (css, js):
- is it better to have less files: ressources are concatenated and minified for each article?
- is it better to keep files that don't change in the whole book separately?
- does it make sense to lazy load some scripts?

Does Baker uses a cache?

Javascript Library:
- does it make sense to replace jQuery by a smaller library like Zepto? (real performance gain?)

Javascript execution:
- is it safe to modify the DOM or to execute some functions before the focus event?

Concerning Baker rendering mode:
- is it faster to use the default mode with screenshots provided or the three-cards mode?

Thanks for sharing your experiences.

**Comment by folletto** [comment]
I don't know the details about the answer, but I can give you some high-level ideas about it.

You have to think in terms of constraints. First of all, on the web you are usually in the situations of a low-bandwidth, high-latency high-memory high-cpu environment. This means that you need to have smaller resources to be transmitted faster, but the cpu and memory execution times aren't usually an issue.

In the mobile environment, on top of bandwidth and latency constraints, you add the memory and cpu ones.

Baker is slightly different, since everything is already local: you have **cpu and memory constraints, but not bandwidth or latency**.

This means that scripts that are smaller aren't necessarily better: they need to consume little cpu and little memory to be perfect. Also, you shouldn't execute multiple animations together, as much as possible, because the mobile CPU might have some difficulties with that.
So, lazy-loading for example could be a good thing to do. Minifying resources not that much. Caching doesn't matter since everything is "already there" (i.e. like in a cache).

About your last question: three-cards mode is better in general, BUT consumes way memory and cpu, so it should be used only if the pages allow for it to run without hitting these limits. :)

I hope it helps. :)

**Comment by benoitchantre** [comment]
Thanks for your detailed answer @folletto.

That means we have to focus on efficient css selectors and efficient JavaScript.

About linked files, I suppose that it should be better to separate specific articles styles in specific files to avoid a lot of useless definitions in one file.
Same thing about plugins: it should be better to include only the plugins needed in one article rather than a concatenated file of every plugin needed for the whole the book.

**Comment by folletto** [comment]
I'm not sure just including a long CSS files make a big difference: executing the rules does, so if the rules don't apply I don't expect a huge performance hit. I wouldn't overfocus on that, even if of course I might be wrong and a test would help clarifying that. :)

**Comment by folletto** [comment]
I'm closing this issue since the discussion seems closed. Reopen if needed. :)
