### ISSUE TITLE
Make that the numbers appear and desappear later than 5 seconds

### ISSUE THREAD

**Issue by molorago** [Simbul/baker#633]

**Comment by Simbul** [comment]
Could you elaborate a bit further?

**Comment by molorago** [comment]
I will like that when the each page load the numeration on the top can desappear in 2 or 3 seconds
its that possible

**Comment by folletto** [comment]
Could you please be more descriptive? It's very hard to understand what you are referring to. What numbers? The page background ones, appearing before the page loads with the spinner? The template ones? Are you using any HTML template? Can you provide a screenshot? What do you want to happen, step by step?

In short, add more details please, otherwise it's impossible for anyone to help you. :)

**Comment by molorago** [comment]
i´m using laker
The numeration in the top on the left side, i would like to make it dissapear afeter some seconds.
THANKS A LOT!

**Comment by folletto** [comment]
Then you should ask on the Laker support site, if it's a Laker-related issue I tink they should be able to help. In general however, if it's just something that you want to add on top of Laker, that said, HTML, it's just a matter of implementing it yourself, so it's just HTML that unfortunately you have to code yourself.

I'm sorry, but we can't give support on the HTML side. If someone else wants to support the comments are open, but I have to close the issue.
