### ISSUE TITLE
Baker 4.0, 4.1 - free and paid subscriptions...

### ISSUE THREAD

**Issue by tablazines** [Simbul/baker#635]
I have an old magazine app that was created by another company that I'm no longer using... and I was trying to wait till Baker 4.1 before utilizing the software since the magazines are paid but publicist who allowed me to interview their artists are getting antsy....

So i'm going to use Baker 4.0 to create the app. I'll allow all the issue to be free up until the time that Baker is updated to 4.1 and from then on I will charge for issues.

Easy enough...

my question revolves around subscriptions.. do they have to be offered?

I don't want to be held to a free subscription once I start charging for the issues...

**Comment by folletto** [comment]
Unfortunately yes, it appears to be a requirement: you need to have a subscription to stay in Newsstand (free or paid) but yes, it's going to be an issue I think with the plan you have in mind... I think. Unless it's possible to say that the "free" subscriptions subscribes you just to certain issues... but I have no idea, I think you should check the documentation and maybe ask on the Apple Dev forums.

**Comment by teckmonkey** [comment]
The way most mags do it is free app download/ subscription..... In app purchase is how you get around that

**Comment by tablazines** [comment]
but teckmonkey, there is no in app purchase right now, correct? 
Folletto, is it possible to offer just 3 month subscriptions then... so that way, when I'm finally able to charge for the issues.. I won't lose too much from the people who subscribed...?

**Comment by teckmonkey** [comment]
I'm thinking this should be possible soon.. Newsstand app requires free option I don't think there is another option

**Comment by folletto** [comment]
Payed Subscriptions _are_ In-App Purchases. IAP include both single issues and payed subscriptions, even if with different mechanisms. Newsstand apps require a Subscription, regardless of the type. We did the free first mostly because doing the IAP part is a long and complex work (not to mention frustrating at times given the communications with the Apple certificates server).

**Comment by teckmonkey** [comment]
Right that's led since

**Comment by tablazines** [comment]
Got it.  Thanks.. Chris "Cartel" English---TablazinesDigital publicationsfor the iPad and other tabletcomputing devices. http://www.tablazines.com1.570.243.1663

-------- Original Message --------
Subject: Re: [baker] Baker 4.0, 4.1 - free and paid subscriptions...
(#635)

**Comment by tablazines** [comment]
But can I only offer a 3 month subscription or am I forced to offer the other tiers as well (6 months, 12 months)?

**Comment by Simbul** [comment]
From the iTunes Connect page to set up Free Subscriptions (emphasis is mine):

> Free subscriptions are a way for developers to put free subscription content in Newsstand. Once a user signs up for a free subscription, it will be available on all devices associated with the user’s Apple ID. Note that **free subscriptions do not expire** and can only be offered in Newsstand-enabled apps.

By the look of it, you cannot offer a free subscription and later on switch to paid subscription.

On the converse, a 3-month subscription cannot be free (i.e. when you set that up in iTunes Connect you _have_ to specify a price).

I guess you _could_ make it clear in the UI that free subscriptions will only get a user so far, and will essentially expire when you introduce paid issues. It is technically feasible, but I have no idea whether it is even legal under your App Store contract. So if you want to take that route you need to take full responsibility for it ;)

**Comment by Simbul** [comment]
Also, just for added clarity: at the present time Baker does not support any subscription other than the free one (so no 3-month subscription, sorry).

**Comment by teckmonkey** [comment]
Right

**Comment by tablazines** [comment]
So Baker's free subscription has no expiration?

**Comment by tstegart** [comment]
Kind of. Apple doesn't want you offering something for free and then taking it away. Its not the "subscription" that matters as much as the content. If you give away an issue for free, the user must always be able to download it again for free, you can't start charging for it later and stop them downloading it again. That is against the rules.

I believe you can change from a free subscription to a paid subscription though. So you would just stop offering new issues for free. The user will still be able to download all the past issues you offered for free, but they will have to pay for new issues.

**Comment by folletto** [comment]
Just to be crystal clear on this: "Baker's Free Subscription", but "Any Free Subscription". It's Apple decision, not ours, as @tstegart explained well. If it was for us, it would have been ways simpler - and better documented. ;) ;) ;)

**Comment by tablazines** [comment]
Yes, I planned to leave all of the issues that were previously available at no cost that way. I would only start charging for new issues once I updated to 4.1

**Comment by tablazines** [comment]
@  folletto Yes I know it's Apple's crazy doing..lol

**Comment by Paul-B** [comment]
Let me see if I get this correctly:
What if I create a newsstand magazine with one isue for free. Maybe two.
Then wait for Baker 4.1 and then start charging for issues that follow while keeping all the previous ones free.
Is this allowed and possible?

**Comment by teckmonkey** [comment]
Good question Paul I'm waiting for 4.1 to FTP befor I come out if the gates 

Tim

**Comment by fanndal** [comment]
I am wondering if I will be able to use Baker 4.1 for a tablet version of a magazine that already has subscribers through web or print? Selling subscriptions through itunes is not really an option at my location as apple does not consider my local market worth much time. I want my subscribers to be able to access an tablet version but we sell subscriptions through our site and hopefully via local magazine vendors.

Is there anyone here that keeps his own subscription database instead of going through Apple. My magazine is tiny and practically a non-profit so using baker instead of having to buy an enterprise edition of Adobe Digital suite ( Since pro only allows for an itunes based subscription ) would allow us to invest more in journalism.

Thanks in advance

**Comment by folletto** [comment]
Apple doesn't handle the suscriptions, you do. 

You might not be doing that because you can just ignore that part in Baker 4.0, but Baker 4.0 pings the server back with the subscription information for your server to store it (see `Constants.h`, `PURCHASE_CONFIRMATION_URL`) and the upcoming Baker 4.1 requires a server to support paid subscriptions and issues (read more on the [Baker Server API page](https://github.com/Simbul/baker/wiki/Baker-Server-API)).

[MagRocket](http://www.magrocket.com/) is an option of a server implementation that supports the Baker Server API. ;)

**Comment by fanndal** [comment]
Folletto, thank you for a quick response. I will check this out. Pardon if my question sounded a little dumb I am new to all this but a quick learner so any links and pointers are a huge help. We havent started using Baker but I am hoping I can convince the others we should.
Thanks again and keep up the good work.

**Comment by folletto** [comment]
Don't worry, every question is useful, because it also helps us to see if we are missing something in our communications, tutorials or explanations (well yes, we lack lots of things, but let's say it helps prioritizing them). :)

**Comment by Simbul** [comment]
Closing as this is probably not relevant anymore, now that 4.1 is out.
