### ISSUE TITLE
landscape orientation: issue not rotated at opening

### ISSUE THREAD

**Issue by benoitchantre** [Simbul/baker#642]
If you have an app that allows both orientations and that contains a landscape issue, the issue is not rotated if you open it when the device has a portrait orientation

![Capture d e cran 2013-01-16 a 11 27 42](https://f.cloud.github.com/assets/1521015/70914/16a7c9ac-5fc9-11e2-8de8-5ea0cb043925.png)

When you rotate the device and then you come back to portrait, the issue is rotated (ok).
If you open the issue when the device has a landscape orientation (ok).

When you double-click to display the index, there's a problem when you come back to the shelf. 

![Capture d e cran 2013-01-16 a 11 47 20](https://f.cloud.github.com/assets/1521015/70925/29905e0c-5fca-11e2-9ffe-17a3f9306f25.png)

**Comment by folletto** [comment]
Thanks, we'll look into it. :)

**Comment by Xm4s** [comment]
Hi @benoitchantre,
I'm aware of the orientation mismatch between the shelf and issues that support only one orientation, and unfortunately I haven't found a solution to the problem.

As you can see the book pages are shown correctly (which is why in your example you see the white space at the bottom of the device) but the device interface is still in portrait. As soon as the device is rotated the interface change to reflect the current device orientation.

The problem is to force the orientation of the interface before the view appear (or right before the view controller is pushed in the navigation stack). I've been looking for a solution to this problem, but so far nothing has worked.

We are opening to suggestion regarding this matter :)

**Comment by benoitchantre** [comment]
Thanks for your feedback and your research @Xm4s.
If it's not possible to force the orientation of the view before it appears, a workaround could be to display a generic content which makes you understand you have to rotate the device?

**Comment by buildc0de** [comment]
It's a bit a over my head, but I've been curios about this issue as well :-) 

I did some tests with triggering **supportedInterfaceOrientations** by [presenting and dismissing a vanilla view controller](http://stackoverflow.com/questions/181780/is-there-a-documented-way-to-set-the-iphone-orientation), which does seem to change the device orientation. However, the app goes haywire after that (-[UIApplication beginIgnoringInteractionEvents] overflow)...

**Comment by buildc0de** [comment]
I wasn't inserting the vanilla VC in the right place :-) Adding it to **'BakerViewController.m | -viewDidLoad'** does work nicely:
- the device is still in portrait
- the app rotates to landscape

There is an issue with -toggleBars, though. On double-tap, looks like the bars appear for a sec and then disappear. Apparently, because -hideBars gets called again. Will play with this further...

**Comment by folletto** [comment]
Wow. :D 
If you are able to fix it, proceed with a pull request so we can review the code and merge easily! :D

**Comment by buildc0de** [comment]
What strangeness. Somehow, the fleeting presence of the vanilla VC turns double-taps into double-double-taps :-)

Double-tap before adding the vanilla VC:

```
2013-01-22 20:55:16.159 Baker[7314:c07] • User tap at [158.000000, 441.000000]
2013-01-22 20:55:16.430 Baker[7314:c07] • User tap at [158.000000, 441.000000]
2013-01-22 20:55:16.430 Baker[7314:c07]     Multi Tap TOGGLE STATUS BAR
2013-01-22 20:55:16.431 Baker[7314:c07] • Toggle bars visibility
```

Double-tap after the vanilla VC has been added:

```
2013-01-22 21:00:30.860 Baker[7367:c07] • User tap at [202.000000, 426.000000]
2013-01-22 21:00:30.860 Baker[7367:c07] • User tap at [202.000000, 426.000000]
2013-01-22 21:00:31.148 Baker[7367:c07] • User tap at [202.000000, 426.000000]
2013-01-22 21:00:31.149 Baker[7367:c07]     Multi Tap TOGGLE STATUS BAR
2013-01-22 21:00:31.149 Baker[7367:c07] • Toggle bars visibility
2013-01-22 21:00:31.151 Baker[7367:c07] • User tap at [202.000000, 426.000000]
2013-01-22 21:00:31.151 Baker[7367:c07]     Multi Tap TOGGLE STATUS BAR
2013-01-22 21:00:31.152 Baker[7367:c07] • Toggle bars visibility
```

As a result, the status bar shows up and immediately disappears. 

What's interesting, this only happens in iOS 6.0. In 5.1, double-tap works normally.

Will continue playing with this...

**Comment by buildc0de** [comment]
What seems to be happening is that presenting and dismissing the vanilla VC causes **BakerViewController.m | -viewWillAppear** to run twice. As a result, it becomes a "double-observer" and **-handleInterceptedTouch** is then executed twice for any single touch notification :-)

To prevent the duplicate observer, I added **removeObserver** before **addObserver** and everything seems to work perfectly :-) I will prepare a pull request later on today...

**Comment by buildc0de** [comment]
Just re-tested everything with a clean project and this requires further work for iOS 5.1. On the very first read, the webview doesn't seem to finish loading the book for some reason. If the book has been previously viewed (before introducing the vanilla VC), then 5.1 works just fine.

All seems well for 6.0, though :smile_cat:

**Comment by buildc0de** [comment]
I think the last implementation fixes this specific issue completely in iOS 5.x and 6.0. The remaining oddities that I'm seeing in 5.x seem to be related to issue #587. I will look into that one next :-)
