### ISSUE TITLE
Baker 3.0 to Baker 4.0 Questions

### ISSUE THREAD

**Issue by sportyguy209** [Simbul/baker#646]
First of all, thanks so much for all of your efforts in developing Baker! Without it, I would have no chance of developing a magazine for the iPad. I'm sure these are elementary questions to most of you, but I would really appreciate your help and I doubt I'll be the only one with these questions.

I'm not a programmer, but am familiar with web stuff like html, css, etc. I developed a magazine using Laker and Baker 3.0 which tests fine through Xcode on my iPad.

Now, I want to move to Baker 4.0 so that I can use Apple's Newsstand and I have read through all the 4.0 instructions and am confused.

My first question has to do with creating the hpubs formatted file necessary. The instructions say the following: "Upload the issues, as zipped Hpubs (remember to zip the files, not the folder), to your server."

Currently all my magazine's (in Baker 3.0) contents reside in a folder named, "book." I assume all the files currently in book (html, css, javascript, images, etc.) are what need to be zipped, but the instructions say not to zip the folder, but to zip the files. Can you please explain what I need to do? I would guess you don't actually have to zip each and every file, but that you would zip the "issue" which would be contained in a folder, but the instructions say not to zip the folder.

Next, what do I do with all the assorted Baker files? Do they get zipped and uploaded to my server separately?

How do I test my magazine through my iPad? With Baker 3.0, I would just send it from Xcode.

With these answers, I can move forward, but I'm not saying I won't have more questions.:-)

A couple of random observations: I found it a bit confusing when, in the "4.0 tutorial for Newsstand," you click on the link for "Book tutorial" you are taken to a page with the heading, "Getting started with Baker Framework 3.2. Because of the version number, I couldn't help but wonder if any of the material has changed or needs to be changed for the 4.0 version.

While I'm not a developer, I can usually figure things out by following an example. Anyway, it would be helpful if the tutorial would take a sample magazine and take the user through the steps to get it "published" and viewable on their ios device. If so, a user like myself would have a clear idea of exactly what they needed to do. At that point it would simply be a matter of substituting files to get up and running with a different magazine.

TIA

**Comment by benoitchantre** [comment]
I can only answer some of your questions because I haven't used the newsstand mode at the moment.

To make an hpub, you need to zip the content that is inside of your book folder, not the folder itself. Select all files and folders inside the book folder (ex: all files inside the folder "a-study-in-scarlet"), make a zip archive from this selection and rename the archive extension to .hpub

To test your issue in xCode, the easiest solution is to have a separated app using the standalone mode. You can follow the instructions from the wiki to use the standalone mode.

**Comment by folletto** [comment]
1. **Hpub** — As @benoitchantre said: just select _all_ the files inside the book folder, zip them and rename the file from "zip" to "hpub" (pay attention to truly rename it, Mac OSX sometimes just hides the extension).
2. **Upload** — Then, you put the _HPub_ files built in this way anywhere on your server, each publication as a separate file, correct. The [shelf.json](https://github.com/Simbul/baker/wiki/Newsstand-shelf-JSON) file you will build (and point to from Baker) will reference all these HPub files you uploaded.
3. **Test** — @benoitchantre gave you an excellent suggestion to test the magazines before working in Newsstand. When you are ready with that, you should then follow the Newsstand tutorial, create the publication on iTunes Connect as said on the tutorial and assign the proper variables. All of this is explained in the Newsstand tutorial. With this, you will be able to test the Newsstand part. 

—

Thanks for the feedback. I think the wiki still needs some more cleanum, and that's a good correction we need to make. The reason is that a book made for Baker 3.2 is exactly the same book you make for Baler 4.0. But it's not that clear I'm afraid. :)

For the tutorial... since we are a bit time constrained... well... I know it's difficult but... may you (or anyone really) want to write it? Your suggestion is again very very valid, it's just we are lacking time. :)

**Comment by sportyguy209** [comment]
Thank you @benoitchantre and @folletto for your helpful answers. Now I understand that the zip file basically creates the enclosing folder for all my book/magazine files.

What is the answer as to the Baker files which reside outside my book file? How do they come into play if I zip my book and the shelf.json file? What do I need to do with them?

TIA

**Comment by sportyguy209** [comment]
@benoitchantre Regarding the standalone app test consideration... I have been using 3.0 Baker to develop the standalone App and it works fine there. Are there any differences in how my App will look, behave, or feature set, if I were to move it to 4.0 or can I just continue to develop and test it in 3.0?

TIA

**Comment by benoitchantre** [comment]
If you really want to test if your issue works well, then test it with the same version (4.0) that you will use with the newsstand mode. It's not difficult to use the standalone mode and you can use only one app to test all your issues.

Like you, I'm not a developer, but everything I know about Baker comes from the website and the wiki.
I can't go to much into technical details for this reason, but it's enough for me as a user of Baker.

**Comment by folletto** [comment]
I'm closing this issue since the discussion seems ended. Reopen if needed. :)
