### ISSUE TITLE
Roadmap of features to be developed

### ISSUE THREAD

**Issue by MacBoy** [Simbul/baker#65]
I have been pleasantly surprised to find new features implemented over the past few months.

I might be able to see a logical path of development from feature to capability that gets implemented.

It would be very helpful if a list of features and capabilities is published.  Then we would know:
- What items would be implemented
- In which order athey would arrive
- Which items we should do on our own in Obj-C or in HTML / JavaScript / CSS

We don't need a schedule, dates or a timeframe.  Just a sequential list of features would be lovely.

I can help by documenting things on a wiki -- let me know please.

Thank you for the terrific work and the lovely surprises!

**Comment by folletto** [comment]
We already have that: the roadmap is this very issue tracker, the order of the items defines the implementation priority (and order) and we use votes, comments and feedbacks to prioritize them. :)

The framework is built to allow you to build a book entirely in HTML/JS/CSS, so that's the overall objective of the project. Anything more than a "book" is Obj-C. :)

We should probably work also on a wiki, or many tutorials, but at this point I think it would be way better if people that work with Baker write about these contents on their blogs and we'll eventually link back. :)

If you want to take that role, you can start writing tutorials and help people that need it. :)

**Comment by Simbul** [comment]
I'm closing this, as the discussion was not developed further ;)
