### ISSUE TITLE
Localised interface

### ISSUE THREAD

**Issue by Simbul** [Simbul/baker#664]
Thanks to pull request #662, it is now possible to create language-specific `Localizable.strings` files.
At the moment the only localisation that comes with Baker is the english one. I'm wary of adding more to the repo because localisations are usually hell to maintain: it's guaranteed that - if we do - we'll end up shipping some version of Baker with out-of-date localisations.

Given that fact, how much interest is there in the community for localised files in the repo?
To be clear, this would mean
- that Baker would come, out of the box, with localised versions of the UI
- that someone who's familiar with each language would have to take responsibility for updating the localised versions

**Comment by benoitchantre** [comment]
I think the english localization included is enough, because language-specific files are difficult to maintain and they can slow down new releases if they are included in the main repository.

If language-specific files are placed in another repository, I think it avoids the problem of out-of-date localizations?
You will be able download langue-specific files from that repository, but you are aware that you have to check if the localized strings you want to include in your app are up to date.
It's less work to have a look at some files than to make them from scratch and that's maybe a solution to keep those localizations shared in the community.

**Comment by benoitchantre** [comment]
@Simbul, I have seen that the german localization has been added to the master repository, but the project has not been updated to use this language.

If you run the iOS Simulator without an update of the project, this language doesn't work.
To make it work, you need to add it from Xcode, but this will result in the error below because Xcode try to create a new file that is already in the folder.

![Capture d e cran 2013-03-28 a 12 07 54](https://f.cloud.github.com/assets/1521015/312912/ca164db4-9797-11e2-9a20-72268a908a41.png)

My suggestion would be to keep localized files outside the master repository, maybe as gist that would be linked from the wiki. When you decide to use a localized interface, you will be forced to check that the localized.strings contains everything.

What do you think?

**Comment by Simbul** [comment]
@benoitchantre you're right, the localisation as it stands won't work. But it would be trivial to add it to the project: just a matter of deleting the file and then adding it again using the steps you followed.

However, while doing some testing I realised there's a bigger issue here. When a localised string is missing for a given locale, iOS will not fallback to english, but rather to the key for that specific translation.
This can lead to a horrible user experience, like the following popup:
![Screen Shot 2013-03-29 at 14 42 41](https://f.cloud.github.com/assets/147104/317744/06e7e1fc-987f-11e2-929b-c1632a6887dd.png)

On that basis, I think your suggestion to keep localisations separate from the main Baker repo is correct. That would at least make it less likely that someone would use an outdated `Localizable.strings`.
I've updated the [Localized interface](https://github.com/Simbul/baker/wiki/Localized-interface) wiki page to reflect that.

@JeanetteMueller sorry for changing my mind after having accepted the pull request. Do you think you could [add your localization](%28https://github.com/Simbul/baker/wiki/Localized-interface#contributing-a-localization%29) to the wiki page?

**Comment by benoitchantre** [comment]
Here's my [french localization](https://gist.github.com/benoitchantre/5291434)
Update: it's now linked from the Wiki

**Comment by Simbul** [comment]
Thanks @benoitchantre!
