### ISSUE TITLE
Page Sorting Problem?

### ISSUE THREAD

**Issue by ffranke** [Simbul/baker#69]
HeyHey!
Is there a problem with the page sorting?
It seems, that iOS is sorting the files the following way:

1.html
11.html
12.html
13.html
2.html
3.html
4.html
.
.
.

Does someone else experience that?

Thanks in advance and best regards,
florian

**Comment by folletto** [comment]
Yep, that's the expected behaviour: the sorting is alphabetical, and alphabetically 11 follows 1, and 2 follows 13. If you want to have the correct ordering, check the suggestions in the readme file (or the example included in the provided book): 01.html, 02.html, 03.html, or proper names: Chapter01.html, Chapter02.html, etc. :)

**Comment by ffranke** [comment]
Hey! Thanks for the quick answer ;)
