### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by vlondon** [Simbul/baker#692]
Hello,
I'm using jQuery to set some effects for pictures in every page. With baker rendering it's not working.
When I'm using 'three-cards' all pages loads before and users can't see what happened after "$(document).ready(function(){". When using 'screenshots' not working after first show.

So, how to fix the code to disable rendering? Thank you.

**Comment by folletto** [comment]
What do you mean by "not working after first show"?

That said, you can use the two events windows "focus" and "blur". :)

**Comment by vlondon** [comment]
I need to show loading and render every page again when user get on it.

**Comment by folletto** [comment]
Ok, but that's exactly what "screenshot" mode does. That's why I don't understand. :)

However as I said, use windows "focus" and "blur" events. :)

**Comment by vlondon** [comment]
You do not understand. Screenshot mode saves page view. But I don't need it. When users on page 3, then swipes to page 4 and then back to page 3 - he don't needs to see saved page static, but some animation that i do with jquery.
I almost solved this with removing few rows from BakerViewController.m
//if ([self checkScreeshotForPage:i andOrientation:interfaceOrientation] && ![attachedScreenshot objectForKey:num]) {
        //    [self placeScreenshotForView:nil andPage:i andOrientation:interfaceOrientation];
        //    [completeSet addObject:num];
        //}

It's did what i need, but on the last page icon of download does not disappear.

**Comment by folletto** [comment]
Ok, let's try again. :)
1. As I said, use window "blur" and "focus" (works in both three-cards and screenshot mode). :)
2. In screenshot mode, you can just provide your own screenshots. Provide empty (maybe even transparent) ones and you're done.

There should be no need to change Baker for that. :)

**Comment by aspek** [comment]
I have some question.
- Why some newsstands app's export from ready-program like Adobe indesign plugin. It short time wait for load new page (Baker take long load If the page have many images although in screenshot mode). And what are type of pages such as baker pages are html.

So, Can "Baker" do like this in future? Or increase Three-cards to Five-cards.

**Comment by folletto** [comment]
I don't understand what you're asking. :)

Randomly:
- Adobe has its own publishing solution, it's called DPS, DIgital Publishing Suite and costs on average 6.000$ per year to start with. They use screenshots, like Baker's screenshot mode and that's why you don't see loading most of the time.
- Baker uses instead HTML5, giving unparalled flexibility and following an open standard. See the HPub standard in the wiki for that.
- We introduced "screenshot" mode because "three-cards" was too heavy to run with rich publication. So I won't expect anytime soon a "five-cards" approach.

**Comment by aspek** [comment]
Thank! for answer.

Is it possible to use "three-cards" and "screenshot" at the same time?

**Comment by folletto** [comment]
No. :) 
But I'm curious, what would you expect to happen using the two at the same time?

**Comment by aspek** [comment]
Sometime Users want to quickly swipe. I need  to show screenshot pages not black screen and preload.

**Comment by folletto** [comment]
Then it's screenshot mode. :)

**Comment by aspek** [comment]
Not at all. Because screenshot mode load every time when the page is  visible(one page).
But three-cards mode can load  /-1/, /current/ ,/+1/  I like this mode but when Users want to quickly swipe. It will show a black screen and preload.  I just  want to change  black screen to screenshot page view.

If is possible the two mode at same time. I think it more complete.
Sorry for my English.

**Comment by folletto** [comment]
Not exactly:
- screenshot mode shows te loading just _once_
- you can pre-load the screenshots so it won't do that even once

Check the wiki for the documentation ;)

**Comment by aspek** [comment]
In my case with screenshot mode.  iPad 2-3
1. At first page I have 60 large images. When open it baker call screenshot "page1.jpg" 
2. the page can't do anything it is during the loading process. Wait for it to finish. And try to play this page.
3. Let's go forward swipe to second page , and do what ever. And I want to play first page again.Backward to first page. Process return to point 1-2  again.

some page I have much more 60 large images. That why I want the two mode at same time. Or am I mistaken.
I have 3 apps from this great framework on Apps store.

**Comment by folletto** [comment]
I don't understand what you are asking. The screenshots are visualized while the page loads, so you don't see any loading after the first time -or- if you provide the screenshots yourself. That's what screenshots are about.

If you keep seeing a loading screen, then there's likely a problem somewhere else. Are you providing the screenshots? Are the screenshots being saved? Did you set the [right pre-rendered screenshots variable](https://github.com/Simbul/baker/wiki/Take-pages-screenshots-for-a-Baker-book)?

That said, having 60 large images per page isn't probably a wise thing to do. Check maybe some [delayed load javascript](http://www.appelsiini.net/projects/lazyload) component.

However, I'm closing this issue since we cleared that it's not a matter of implementing a new feature. :)

**Comment by aspek** [comment]
Um.. look like I'm not clear. 
However some day I will provide an interpreter to translate my true problem. And record it on youtube.
Thank you so much. And thank this frame work make the world grow up.
