### ISSUE TITLE
Javascript event: user scrolled down till the N-th page

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#695]
Hi all!
Let's assume, we've got some html-chapters in a book,
each of them is quite long, and we're using 
"-baker-vertical-pagination" parameter to allow user scroll the long pages more comfortable.

So, in this case, is there any javascript event available, say,
"user scrolled till the N-th page of the current paginated chapter"?
So, that when user, after opening a long chapter scrolls down by a page (splitted automatically by Baker's option) we have a javascript event for each "scroll down"...?

**Comment by folletto** [comment]
Hi :D

There's no special event, because you can do that with the standard set of HTML events (scroll) and variables ([scrollY](https://developer.mozilla.org/en/docs/DOM/window.scrollY)).

You can quite easily monitor that and with some math generate an event every page scroll (you could even probably build a library for others). :)

**Comment by divlv** [comment]
OK, thanks for hint.
I'll try to create and share the javascript code for that.

**Comment by Simbul** [comment]
@Dinamitrij any news on this?
