### ISSUE TITLE
Moving Past "Baker Shelf"

### ISSUE THREAD

**Issue by jjinaustin** [Simbul/baker#702]
Hi all,

I am really excited about the possibilities of working with Baker but I am having a bit of trouble getting started unfortunately. I am admittedly a newbie with the framework but have tried to do my diligence troubleshooting a number of areas before posting. I have been at it a few days and though I hate to do it, I thought at the risk of my sanity, I would go ahead and ask for some help.  I am using Baker framework version 4.0 and have the latest version of Xcode version 4.6.  I am simply trying to load the Baker example book "A Study in Scarlet" so I can code from there or with Laker.  I have been following the Newstand tutorial (that is my preference) but I can't seem to move past the front page or load any of the HTML pages created to test. Basically, just the white screen with the Baker logo that says "Baker Shelf" at the top.  

For a while, I was having the same issue #626 with "no internet connection error message" and I have read the issue quite a few times. I was able to get rid of the message by putting in my local host as addressed but still the same static page.  I have tried plugging in the Laker "book" file as well with no luck. Issue #646 is also similar and tried some of the suggestions there as well. I have a feeling it has something to do with the shelf.json/manifest, assigning a proper URL as in #626, or proper placement/preparation of the hpub file (or maybe something else completely obvious). Following the "First Build" section part of the tutorial it seems like it should be working after I set the scheme and hit run, so I am stumped.  I have read the newbie questions and gone step by step through the debugging process as well with no luck. Any help or ideas would be much appreciated and am very happy to answer any questions you might have. Thanks very much.

**Comment by folletto** [comment]
First: thanks for having tried to solve the problem to such extent before posting. It's uncommon and you deserve credit for that. :)

One more think I might ask before trying to debug... could you post here the details we ask in the [Problems and Debugging page](https://github.com/Simbul/baker/wiki/Problems-and-Debugging) (steps, log)?

My guess right now is that you followed the tutorial for version 3.2 instead of the one for version 4.0, here: 
https://github.com/Simbul/baker/wiki

**Comment by jjinaustin** [comment]
Thanks very much for the prompt response! Yes, that was strange. I was getting redirected to the older version for some reason , though I was clicking on the link for 4.0 version. It literally changed before my eyes. I am going through the new tutorial now and will definitely do a step-by-step, log, etc. if any issues arise. Thanks!

**Comment by folletto** [comment]
The old link was there, but it meant to refer just to the first part of the tutorial. After your message we took it out and separated properly. As many things here it's always a matter of having time to do things, so feedback is critical, thanks. :D

**Comment by bryanrpi** [comment]
I too have exactly the same problem jjinaustin posted namely: 
"I have been following the Newstand tutorial (that is my preference) but I can't seem to move past the front page or load any of the HTML pages created to test. Basically, just the white screen with the Baker logo that says "Baker Shelf" at the top."

I am using xcode 4.6 and Baker 4.0

I am confused as to what files I am supposed to load into the folder 'books' and have tried the following:
a) Loaded the individual files of mybook directly into 'books'.
b) Loaded the folder mybook into 'books'.
c) Loaded the folder mybook into 'books' and changed mybook name into 'book'.
for all these, I still get a white screen with the Baker logo that says "Baker Shelf" at the top.

I followed the steps on the The Problems and Debugging page and it lists:
"5) If it still doesn't work, try testing the MASTER version from GitHub: while it's not considered stable, sometimes it solves the issue."  - How do I find that on GitHub please?

P.S. Mybook simulates perfectly in BakerFramework 3.2

**Comment by folletto** [comment]
I think we have to make a step back. :)
If you are following the Newsstand tutorial (from the wiki page above) you don't have to put anything in the book folder: you are using Newsstand, so all the issues are remote on your server.

Please follow through the Newsstand tutorial from the very beginning, step by step. :)
https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand

**Comment by bryanrpi** [comment]
Thank you for your guidance folleto I have followed the tutorial instructions:

the last instruction in the Newsstand tutorial is: "When you're ready, submit to the App Store."

Just how does one do this?

Application Loader  first asks me to choose  and asks me for my only application, namely: "Inspirations on Peace and Joy - Sampler"

Next, it asks me to choose what file to upload! This is where I am stuck because I have no idea where to find an appropriate file to upload. Where does the Baker Newsstand xcode fit in?

I have the hpub file on my url: http://www.dancinginthemirror.com/ebooks/inspirainssampler.hpub. Where does this fit in?

**Comment by folletto** [comment]
To do that... you need to have an Apple Developer Account, all the instructions on how to do that are on Apple's Developer website. :)

The Newsstand tutorial should have already answered your second question: the Hpub is downloaded from the app, given what you wrote in the `shelf.json` file. :)

**Comment by moloragom** [comment]
i follow the tutorial and still dont know how to begin

**Comment by bryanrpi** [comment]
I do have an apple developer account and have entered all the data for my two apps. The status of both is "waiting for upload".

How to do this is, as you say, an apple procedure. So my question isn't 'How' it is 'What' do I upload?

**Comment by folletto** [comment]
Please @bryanrpi you have another thread to follow up (#711), don't post in this one since it's another person's issue. :)
That said, please refer to Apple's forum, Apple's documentation or StackOverflow. Or well... the tutorial I linked you already in Issue #711. This is Apple's support matter, not Baker. :)

**Comment by bryanrpi** [comment]
Thank you Davide,

I will explore in those mediums - I suspect is it is an xcode issue about
setting the release flags.

Bryan

-----Original Message-----

**Comment by Simbul** [comment]
@jjinaustin I'm about to close this thread, as it has become stale by now. Have you solved your original issue?

**Comment by jjinaustin** [comment]
Yes, thanks very much. Issue is resolved. Thanks again!

**Comment by Simbul** [comment]
Great! :)
