### ISSUE TITLE
securing in app purchase content

### ISSUE THREAD

**Issue by surelynot** [Simbul/baker#715]
Something that has been bugging me in looking at providing In App Purchasing when Baker 4.1 is released, is how one either hides or secures the .hpub content on one's server. Has anyone been looking into this? At present someone could fairly easily sniff the link to the content when purchasing and distribute it (and potentially guess the paths to the other issues they haven't purchased, or get them from the remote .json file if in the same folder).

There seem to be two lines of thought to prevent this, having done some searching (I have little idea about this stuff):

Firstly, by randomising the path to the content (see here):
http://stackoverflow.com/questions/5609861/securely-downloading-in-app-purchases?rq=1

Secondly, encrypting the content on the server, which is decrypted on the fly (maybe with keys provided via the purchase validation receipt?), apparently Apple supports CommonCrypto within the iOS SDK:
http://stackoverflow.com/questions/5064144/correct-and-secure-manner-of-storing-in-app-purchases?rq=1   

Has anyone been working on this, or have any thoughts? Decrypting large issues on the fly, especially with early iPads, could be real problem right?

**Comment by Simbul** [comment]
Security is always a trade-off, as those threads on StackOverflow correctly point out. You have to get the right level of security to discourage widespread breaking of your rules, but on the other hand you don't want to build a very complicated system, as it would (a) eat up a lot of your development time (b) make the management of purchases more complicated for you and (c) make life harder for legit users.

The current state of affairs, afaik, is that you can't trust anything you put on a user's device. That goes for cryptographic keys as well, which is why I think the CommonCrypto solution is not a good trade-off at the moment.

However, I've been thinking about this and I'm looking into implementing a simpler security layer.
When the new [paid-subscriptions](https://github.com/Simbul/baker/tree/paid-subscriptions) branch gets merged, users will have their own unique ID, which will look something like `920B0F9A-DDFB-4DB6-BF93-DF742E9AE20D`.
Download requests coming from Baker will include the `user_id`: the server will then be able to inspect it and allow download only if the user has the right to access the content.

This won't stop someone from sniffing network traffic, figuring out their personal URL and distributing it. On the other hand, you may implement a throttling mechanism on the server to prevent too many downloads coming from different IPs for the same `user_id`.
It goes without saying that, if you want to use this feature, your server will have to be more clever than just a simple FTP storage.

I know it sounds corny, but the best way of securing your content is making sure that it's great and users actually want to pay for it and support your work. And implement a thin security layer so that most of them can't be bothered to choose the dark side ;)

**Comment by nin9creative** [comment]
Didn't this conversation come up about a year back? ;)

**Comment by folletto** [comment]
Yep. It pops up in pretty much every field once every few months. ;)

**Comment by surelynot** [comment]
Hi Andrew,

yes it was brought up (indeed by you) but there wasn't any discussion apart from an opinion to ignore it. I actually raised two differing approaches to implementing some smoke and mirrors to avoid easily discovering the content folder (one of which, CommonCrypto, am I correct that you implemented this in your RocketMag project? I saw some reference to it in the code, but you haven't mentioned it here or in relation to the previous issue – is that what you're now using?). I did so in the hope it might be discussed further now we're a lot closer to a working IAP-shelf Baker than a year ago.

It's fine to say make the content good and no-one will steal it, and I agree no DRM or security should get in the way too much, but I think there's an argument to make it slightly less porous than it currently is. Part of our undertakings with the publications we're doing is to reproduce the artwork (including video and sound) of a number of artists with their permission, which is going to be difficult to get if it is very straightforward to access and steal the original files (particularly the 720p video works which could be individually resold, perhaps hurting the artist's market).

Anyway, just saying it's a concern to me, and perhaps it will be if Baker is used more widely in this area by a broader range of users. I think the simple server authentication that Simbul raised and is considering would probably allay the fears of most, even if it's not perfect a thin layer of security is more appealing than none.

**Comment by folletto** [comment]
As said before, the point is a matter of effort/efficiency ratio. ;)
Feel free to implement the features and feed back the code to Baker, if it doesnt make the process more complex, we'll be happy to merge it. :)

**Comment by Simbul** [comment]
Since commit e3e7c7b38fe6caba5ad881d2919abc61cdd77d9b, Baker sends the `app_id` and the `user_id` with each download request.
This means that the server can implement an access policy to only allow downloads for users who have purchased a given issue. See the [issue endpoint](https://github.com/Simbul/baker-server-example/blob/master/issue.php) in [baker-server-example](https://github.com/Simbul/baker-server-example/) for a sample implementation.

As for encrypting content, unfortunately we don't have the time to implement such a solution at the moment. Pull requests are welcome :)

In the interest of housekeeping, I'm closing the thread, as I think the security mechanism explained above is the only one we can reasonably implement given the available time.
