### ISSUE TITLE
Opening a local HTML in modal window

### ISSUE THREAD

**Issue by jukialla** [Simbul/baker#761]
Thanks for a great framework. I am almost complete with my first app and hope to push it out soon. Its basically a travel guide with maps using Leaflet. Users can zoom within a map to any lat/lng and tap on a marker. I want them to be able to open a local HTML file in the modal window (as a popup) and then return to the referring HTML page with zoom and lat/lng intact (as it would with an external link - which it also has). I can implement internal links, but want to make the process for both (internal and external) as consistent as possible. I also can save the zoom and lat/lng and restore on a page refresh, but that is clumsy. Any chance of implementing internal links in the modal window like the external links? Am I missing anything?

(Related to #617 and #609)

**Comment by folletto** [comment]
Thanks for the feedback. :)

I'm not entirely sure about the feature, because if you want to do that you could simply open an overlay using a lightbox (for example with the [Lightbox 2 library](http://lokeshdhakar.com/projects/lightbox2/) ) and this way is already doable and more aligned with Baker's concept of using HTML5 as the book structure with minimal interventions. :)

Let me know if the lightbox solution works for you. :)

**Comment by jukialla** [comment]
Thanks for that. Lightbox wasn't suitable as it appears only suitable for images. However I found JQuery Tools Overlay which seems to be doing the trick ok. I'm a complete noob at this, so I'm discovering all sorts of wonderful things.
