### ISSUE TITLE
Detecting Low Memory Warning

### ISSUE THREAD

**Issue by jukialla** [Simbul/baker#767]
I have been reducing the memory footprint of my 1st standalone app as much as possible. I get a low memory warning on an iPad 1 when I try to load a LightBox (fine on iPad2). I'm sure I can reduce the memory demand of the LightBox, but how does one detect (in Baker/JS) a low memory warning in the first place? Is it an Apple requirement that apps respond to such warnings? I can respond accordingly if I could detect the warnings. Or should I just make my app as lean as I can and ignore the warnings. However I would like it to crash gracefully if IOS decides to give it the boot. 

I can't seem to find anything here. Any advice would be greatly appreciated.

**Comment by Simbul** [comment]
As far as I can tell, there's not much we can do for memory warnings on an iPad1.
Memory management in Baker could be a lot better, but even if we plug all memory leaks I don't think we'll be able to avoid all memory warnings on such an old hardware (I know something about it: I own one :D).

Other than printing warnings, is your app giving any trouble (e.g. random crashes)?

**Comment by jukialla** [comment]
The app is fine on the iPad1, it doesn't crash and when I close other apps in the background, the warnings don't appear. So I'm not overly concerned about it. I have read that Apple require apps to be able to respond to such warnings though ie-http://developer.apple.com/library/ios/#documentation/iphone/conceptual/iphoneosprogrammingguide/PerformanceTuning/PerformanceTuning.html

But I guess that there have been many Baker apps through that don't have that capacity to detect and respond to LMW.

**Comment by folletto** [comment]
You're quite correct. That part regards the Objective-C side of things. 
It's not about the HTML side you (and most of the authors) work on. :)

In more technical terms and probably answering your initial question, there isn't much we can do if it's the page that is consuming the memory, because it's all handled by the `UIWebView`, and that for us behaves mostly like a black box. Since Baker is just slightly more than a `UIWebView`... the only thing you can do it optimize the HTML page itself.
