### ISSUE TITLE
Adding Content Category

### ISSUE THREAD

**Issue by schamas** [Simbul/baker#785]
Hi there,
First of all i would like to thank you for this application framework. Thats really cool stuff. 
I analyse framework but i still cannot find content category system 
Also i need Search button. 
I need something like Zinio. 
For example; 
Books, magazines, news, catalogs tab's will be in application. 
Books tab has, 
child books, academic books, sport books, novels, bestsellers etc. 
magazines has different style of magazines, 
fashion, sport, cars, computers etc. 
news tab has newspapers. etc. 

Search Button and Category system needed.
Please help me how can i add these?
Thanks for your help

**Comment by folletto** [comment]
Hello, thanks for asking. :)
1. Search is not implemented, it's tracked by issue #61
2. Categories aren't part of Baker and they aren't currently in our plans, since they are for a generic reader and not for a publication.

If you need both, the best way right now is to develop them yourselves.
You might try to contact one of the developers in our Developers page if you need support:
http://bakerframework.com/developers

Thanks. :)

**Comment by schamas** [comment]
Hi Folletto, 
Thanks for your answer my friend. I will send email all to your developers. 
This is the cool framework. I am happy to find it. 

Have a nice day :)
