### ISSUE TITLE
PDF pages to PNG/JPG then HPUB. How?

### ISSUE THREAD

**Issue by biapar** [Simbul/baker#802]
Hi,
I've a PDF magazine that I wish to port to HTML5 magazine ( HPUB ).
So, I converted each PDF page to PNG and JPG image.
Do I create HPUB file or HTML5 mag?
Thank you.

**Comment by coosir** [comment]
create html pages to show the images, then create hpub file

**Comment by biapar** [comment]
Ok, but are there some hints? Is it possible to zooming?

**Comment by ask91** [comment]
You can edit "zoomable" parameter on your book.JSON file for two value, TRUE or FALSE.
follow there for more standalone configuration--> https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Standalone
or here for newsstand configuration--> https://github.com/Simbul/baker/wiki/4.0-tutorial-for-Newsstand

**Comment by coosir** [comment]
I converted pdf pages into jpg files, and included them in html pages.
baker would crash somtimes when reading magazines with lots of large jpg pages...I mean, very often

**Comment by folletto** [comment]
Large images mean lots of memory consumption and as such you're likely over the hardware memory limit. The only way out is to reduce memory consumption - that's also a reason why you should really use HTML to build the magazine and not just images. ;)

**Comment by ask91** [comment]
Besides, HTML enriched with CSS animation or javascript will simply provide interactive magazine for your users :)

**Comment by biapar** [comment]
Can you convert PDF to HTML?

2013/4/13 ask91 notifications@github.com

> Besides, HTML enriched with CSS animation or javascript will simply
> provide interactive magazine for your users :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Simbul/baker/issues/802#issuecomment-16322071
> .

## 

Cordiali Saluti / Best Regards

Ing. Biagio Paruolo

Red Consulting s.a.s
Via Garibaldi, 1/B - 83025 Montoro Inferiore ( AV ) - Italy
Tel: +39 3928196008 Fax: +39 36 3928196008
Web:  www.redconsulting.it
Email: biapar@redconsulting.it / MSN: biapar@inwind.it / SkyPe:
biagioparuolo

Microsoft Partner and Cloud Partner | Web and Mobile Solutions | Register
Gold Reseller

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by ask91** [comment]
i never tried converting PDF to HTML. But, we can convert  it with some softwares.

back to your intention of  'How you want to maintain your publication'
-Do you want just publish it? as a portfolios?
  you can do as you did. include images in all HTML pages, convert a pdf to HTML with any HTML software converter.
or
-Do you want to learn more the result of your publication, like knowing the feedback, analitics, tracking etc.?
  then i suggest to use the HTML publication with some 'human codes' of HTML CSS and Javascript on it (not a software converter) - https://twitter.com/ardini91/status/309706471568977921 -
semantic HTML creates by human-brain-codes are more SEO friendly. 
Those SEO , analytic reports, will help you a lot, -if you;re in-  a bussiness/marketing publications.
you should consider them to focusing on your users target market and improves the publications to earn more benefits. :)

**Comment by biapar** [comment]
I agree with you, but I've pdf file only from the customer and rewriting all magazine in html it's a big work. So I wish to start from a converted base from pdf. Other problem is that each month there is a new magazine number  , so there is not a lot of time to adjust converted html.

Inviato da iPhone

Il giorno 13/apr/2013, alle ore 11:07, ask91 notifications@github.com ha scritto:

**Comment by ask91** [comment]
So you want to already have the HTML layout from pdf, and then modify those HTML pages ?

There're lots of PDF-to-HTML converter softwares, im not sure i allowed to say those brands here [since i'm new at these forums & not really understand the ethics],
have you checked the link i sent above? that will bring you to what kind of software converter you might use in your project.

hope that'll help :)

**Comment by biapar** [comment]
Yes. I want convert Pdf to Html. I try to convert it to Png with PdfCreator and I've a good result. Then I create an Html file and put in png file with css as layer full image background.

Inviato da iPhone

Il giorno 14/apr/2013, alle ore 03:51, ask91 notifications@github.com ha scritto:

**Comment by benjamincano** [comment]
I tried several exports and PNG 768x1024 pixels worked for me, its a fixed size so no zoom, but it can handle about 100 pages like that.

**Comment by benjamincano** [comment]
I tried several exports and PNG 768x1024 pixels worked for me, its a fixed size so no zoom, but it can handle about 100 pages like that.

**Comment by biapar** [comment]
musuko Have you an example of your hpub? How customize 100 html file to include your png?

**Comment by benjamincano** [comment]
My JSON looks like this... i made the images 768x1024 because of the size the files were huge and rendering was slow. In my case I only wanted to make it work with iPad on portrait mode and its not zoomable.

```
{
    "hpub": 85,
    "title": "Number 85",
    "author": ["Mag"],
    "creator": ["Mag"],
    "date": "2013-03-01",
    "url": "book://example.com/e085.hpub",
    "cover": "e085.png",

    "orientation": "portrait",
    "zoomable": false,

    "-baker-background": "#ffffff",
    "-baker-vertical-bounce": true,
    "-baker-index-height": 0,
    "-baker-media-autoplay": true,
    "-baker-background-image-portrait": "images/background-portrait.png",
    "-baker-background-image-landscape": "images/background-landscape.png",
    "-baker-page-numbers-color": "#ffffff",
    "-baker-rendering": "three-cards",

    "contents": [
        "001.html",
        "002.html",
...
```

Then I created a template folder and made a 100 htmls... I created them one time because if the magazine has less pages I can easily remove pages instead of creating them each time. So each HTML file is named with the page number "075.html" for example.

```
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title></title>
<style>
body {
    -webkit-background-size: 100%;
    -moz-background-size: 100%;
    -o-background-size: 100%;
    background-size: 100%;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    background-attachment: fixed;
    background-image: url(pages/075.png);
    background-repeat: no-repeat;
    background-position: center center;
    }
</style>
</head>

<body>
</body>
</html>
```

If you see the html is pretty simple it takes the images from the pages folder and stretch it (if portrait mode was not activated and you turn it, it will look bad) I store all the images inside a folder and they're named with numbers so there is no redoing of html files every time.

Since it can be a tedious process I read the files from a PDF and I can open all the pages at once, I created an action so it changes the size and export the file as PNG to a folder. Since the file exported has a number I use a tool called Renamer for mac and just add or remove so it fits my needs and then i just pack it and upload it.

**Comment by biapar** [comment]
Good. If you interested I create a Node.JS script

**Comment by benjamincano** [comment]
Yes please, I knew there most be a better way I didnt know how.

**Comment by biapar** [comment]
Here is: https://github.com/biapar/NodeJS-Html-Generator

**Comment by biapar** [comment]
@musuko: Have you tried?
Which action have you created on Mac to export from PDF?

**Comment by benjamincano** [comment]
Sorry, I didn't specified I use Photoshop. Since the task can be time consuming Photoshop lets you open PDF with several pages at once (it can consume a lot of memory though), when the dialog box opens I specified the 768 x 1024 size so it wont load the original files instead which can be bigger, also i change the name from there also with a base name like "edition8" Photoshop will add a number at the end. My action pretty much takes one layer and saves them as PDF and saves it on a folder i specified and then closes the image and moves to the other one and so on.

Feel free to e-mail me @gmail, same nickname. I just had time to look at the code, I am planned to try it later today :)

**Comment by folletto** [comment]
Good advices. :)
However I'm closing this discussion since more than a month passed. :)

**Comment by biapar** [comment]
Sorry, but I don't try the suggestions, yet.

Saluti
ing. Biagio Paruolo
Inviato da iPhone5

Il giorno 26/mag/2013, alle ore 16:04, Davide Casali notifications@github.com ha scritto:
