### ISSUE TITLE
Auto Renewable Subscriptions

### ISSUE THREAD

**Issue by ImkeTee** [Simbul/baker#810]
I am setting up in-app-purchase for newsstand through Baker and I am wondering if you have to add a Free subscription as well as apaid for 1 year subscription? And if so what will the Free subscription contain? 

At the moment I have added the Issue (Non-consumable) and a 1 year supscription on iTunes. Do I need to add an extra subscription that has no Tier for pricing selected? 

Thanks for help.

**Comment by folletto** [comment]
Subscriptions are in theory the same as the "physical" thing. If you're selling a magazine and you have subscriptions, you use them.

Apple mandates free subscription as the "minimum" thing to appear on Newsstand, but of course if your magazine is a paid magazine the understanding right now is that you have just the paid one (since otherwise you'd be giving away your magazine for free when it's not). :)

Apple then can be interpreting differently things at the moment of the submission approval process, but well, this should be the correct answer. :)

**Comment by ImkeTee** [comment]
I figured it out too. :o) The wording was just a bit confusing. Many thanks tho

**Comment by folletto** [comment]
Great. :)
You're welcome. :)
