### ISSUE TITLE
crash when reading magazines with large pictures

### ISSUE THREAD

**Issue by coosir** [Simbul/baker#832]
some magazines have large images, 1~3M per image/page.
this would lead to crash (often).

can you try to improve memory handling ability of baker?
large images are needed for some magazines anyway.

Thanks for your great work!

**Comment by folletto** [comment]
Unfortunately we can't do much when there are big images, because these are handled by the WebView component and that's Apple's. We are already doing a lot of optimizations there, and new ones are added every version, but we have very little space of maneuver there.

There are some things you can do to optimize that, but overall it all depend on how big is the page you're building.

I'm sorry.
