### ISSUE TITLE
Little question about Refresh Button

### ISSUE THREAD

**Issue by kodjoe** [Simbul/baker#833]
Hello Everybody ;) 

Just to know, When I update my shel.json by changing a sentence for example. 
is it normal that anything change after clicking  on it ?
there is any sign who show me that I clicked on it or that my contained load after that ?

for example -> wheel of loading

Thank you

**Comment by folletto** [comment]
Well... if it updates, the content of the shelf updates... no? :D 
What are you thinking of exactly? :)

**Comment by nin9creative** [comment]
Actually, if the button at least reacted to the touch in some way that would be useful.  Right now even in testing on my iPad - it seems "unresponsive" when clicking on it - but it does refresh the display.

**Comment by kodjoe** [comment]
Hi guys,

that's exactly this Andrew, In fact we have no evidence of loading if we press the button, any sign who prove that the content has been actualized ?

Contrary to the subscribe button, check my image, you can see the difference between the
two subscribe button before and after clicking on it  ->

![000](https://f.cloud.github.com/assets/4087173/415534/81273d3a-ac36-11e2-8063-518e2577f8f1.jpg)

I want to know if there is a possibility to change the color of the button when we click on it, because as nothing happens after clicking. I think that a reader can think that the button is inactive because he has no idea  about the date of the contents update

Hope you understand me ;)
If you have any suggestion to add you can close this issue ;)

**Comment by folletto** [comment]
Believe it or not, but we tried already, a few times. It _does_ disable while refreshing (`[self setrefreshButtonEnabled:NO];` in `ShelfViewController.m`) but it just doesn't show up... because it's black apparently.

We weren't able to find a simple solution to fix it, and other items got prioritized since it was a lot of work compared to the benefit. But yes, it's a total annoyance. :D  

If anyone wants to try fix it, we'll gladly accept it. :D

**Comment by kodjoe** [comment]
Aie I understand and you're right this is a low priority ;D
Okay for me big thanks I've had my answer ;)

**Comment by benoitchantre** [comment]
I had the same feeling that the button was not working because of a missing state when clicked.
When you have no internet connection, the button works the same way, except the shelf can't refresh itself.

My suggestion would be to remove the button but to keep the feature:
- if the shelf automatically refresh itself when you open the app or when you come to the shelf, there's no need for a button
- if a manual refresh is absolutely needed (for developers?), it could be done with a pull to refresh on the shelf

What do you think about this idea?

I know there are a lot of features more important than this one.

**Comment by folletto** [comment]
I think it's just simpler to make the button's state more evident. ;)
Removing the button is an option we considered, maybe in the future.

**Comment by benoitchantre** [comment]
Thanks for your feedback.

**Comment by folletto** [comment]
Thanks to you! You're very passionate and helped a lot through a lot of issues. :)
