### ISSUE TITLE
Problem with IndexViewController

### ISSUE THREAD

**Issue by Alua-Kinzhebayeva** [Simbul/baker#900]
Hello!

I am using version 4.1.

I have noticed that sometimes IndexViewController moves up and disappears if you touch it and move it up without lifting a finger. 
Sometimes it happens to both sample hpub book and my custom hpubs. Sometimes it happens to custom ones only. That is what makes it so confusing. 

Have anyone had such problem? If so, could you share your thoughts on this matter?

Thank you,
Alua

normal state:
![screen shot 2013-05-21 at 4 31 30 pm](https://f.cloud.github.com/assets/3368528/541249/8123f228-c203-11e2-9976-93461ee166d2.png)
strange state:
![screen shot 2013-05-21 at 4 31 44 pm](https://f.cloud.github.com/assets/3368528/541253/9ea17500-c203-11e2-8450-970856eb067e.png)

**Comment by folletto** [comment]
It's mostly a matter of how the index HTML is built. The page seems with transparent background and higher than the container and if that's correct that's the reason why you can slide it up. If you try a different HTML you should be able to have the index to avoid scrolling.

The IndexView is just a UIWebView: if it scrolls, it's because the HTML scrolls, as it would in a normal page.

**Comment by Alua-Kinzhebayeva** [comment]
thank you.
