### ISSUE TITLE
Subscribed, but button keep saying: "You are not subscribed"

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#920]
I'm trying to setup free subscription,
from iTunes side everything looks OK (it seems to me :-)  ) 
but on the App side I can't understand what I am doing wrong...
So,
I touch the **[Subscribe]** button and press the **[Subscribe for free]** button.

![Go, subscribe](http://is.gd/EtVBeo)

After process finish (entering an account, agree with conditions, e.c.t.)
I've got a confirmation:

![Subscribed OK](http://is.gd/ejXJ0E)

I even got a new record in my **RECEIPTS** MySQL table.
It's OK.

But I noticed that top  **[Subscribe]** button has not changed its look,
and when I press this button again I see the following:

![Not subscribed](http://is.gd/FLogSb)

It says: "You are not subscribed" ( _and no more button visible_ )

So... the question is: what I am doing wrong?

**Comment by folletto** [comment]
Did you specify the constant `PURCHASES_URL` and do you have the server replying to that correctly?

**Comment by divlv** [comment]
Thanks, @folletto , your idea is right!
`PURCHASES_URL` was of course filled, but the reply wasn't correct, and I found why:

in your sample code of Baker Server API, in **purchases.php** 
at the top of file there is a DB Select:

`"SELECT receipt_base64 FROM receipt WHERE receipt_appid='$app_id' AND receipt_userid='$user_id'
 AND receipt_type='auto-renewable-subscription' ORDER BY receipt_transactionid DESC LIMIT 0, 1"`

This select **returns nothing**, because my **receipt_type was "free-subscription" and not "auto-renewable-subscription"**

Hmmm... why so?
Should I change this select?
But... if I plan to sell the future issues ( _keep only several free issues, but the others - for money_ ) how should I act in this case?

**Comment by Simbul** [comment]
Please keep in mind that baker-server-example is, as the name implies, only a sample implementation and it should not be used in production.

The server example only implements a simple case, where all subscriptions are auto-renewable. Supporting both auto-renewable and free subscriptions requires a different logic, as you need to decide which issues will be covered by the free subscription and which ones by the auto-renewable subscription.

The server API for [PURCHASES_URL](https://github.com/Simbul/baker/wiki/Baker-Server-API#purchased-issues-and-subscriptions) specifies that the returned `subscribed` parameter indicates whether a subscription is _currently_ active for the user.
Since free subscriptions basically never expire, that's another piece of logic you need to build in (I guess you want your users to be able to set up a paid subscription even when they've subscribed for free in the past).

**Comment by divlv** [comment]
OK, thanks, got it.
