### ISSUE TITLE
What is baker?

### ISSUE THREAD

**Issue by jriker1** [Simbul/baker#923]
I may have missed it but the faq didn't have a "What is Baker?" item. Is baker strictly a hook into apples newsstand to distribute publications purchased thru iTunes?  

If so, what is the standalone version?  I am looking for a way to distribute articles in my organization without apples involvement. Note I have an enterprise certificate. I know the standalone says one publication only so not sure that's ideal but curious how it works if I wanted to distribute multiple publications and update them when changes are made, if this could do that. 

Thanks. 

JR

**Comment by folletto** [comment]
Baker is a HTML5 ebook framework to publish interactive books and magazines in iPad and iPhone using simply open web standards. :)

Baker is first and foremost that: you design books or magazines in HTML5 (using the HPub format) and it allows you to publish them. Depending on your need, you can publish these HPubs with Baker inside Newsstand or as a Standalone app. Your choice. :)

**Comment by jriker1** [comment]
Thanks for the reply. You managed not to mention iTunes at all. :). Is the newsstand publications and the standalone not requiring iTunes?  Also if I have two publications or three or four in standalone will I need two or three or four instances of the app running?

Thanks.

**Comment by folletto** [comment]
I managed because it seems from the question that there were a misunderstanding. I'll try to be clearer: there's no such a thing as "publications purchased thru iTunes". :)

You can have:
1. books published as ebooks on the Book Store
2. books published as iBook Author on the Book Store
3. books and magazines published as standard, standalone applications in the App Store
4. books and magazines published as Newsstand applications in the App Store
5. books and magazines published as standard, standalone applications in an Enteprise Store
6. books and magazines published as Newsstand applications in an Enterprise Store (not entirely sure about this)

Each one of them is built and handled differently. Given you spoke about "distribute articles in my organization without apples involvement" with an "enterprise certificate" you don't deal with neither iTunes or the Store at all, so Baker or not Baker, iTunes isn't involved as much as it isn't involved with any other Enterprise Store app. 
And actually iTunes isn't involved in general, because each one of the channel is a Store (either Book Store or App Store) while iTunes is just one of the many ways to access it. Unless you mean iTunes Connect, and that's then the case for the points 3 and 4 above. :)

So, to be able to answer you properly, I need to know what you're trying to do exactly, because at this point it's a bit too vague. :)

And to answer you last question: depends. You can do one app containing all of them, or one app for each. Again, depends on your objective. :)
