### ISSUE TITLE
Zoomable: true , change page size

### ISSUE THREAD

**Issue by Chrissmen** [Simbul/baker#935]
Hi , im using the bakerframework, but when i want use zoomable = true in my book.json
the page change to -30% size avrg, and zoom  work , but i need begin the page visible to 100% of the screen or page to fit, somebody know about this issue?
thanks , attach my examples in simulator is the same issue with device
![captura de pantalla 2013-06-03 a la s 19 30 31](https://f.cloud.github.com/assets/4357181/602997/2923109e-ccae-11e2-881a-fda56d23667d.png)
![captura de pantalla 2013-06-03 a la s 19 31 11](https://f.cloud.github.com/assets/4357181/602999/6d09c938-ccae-11e2-9389-e54f4a0ee280.png)

**Comment by folletto** [comment]
Before answering: we usually advise strongly against using zoom, because it usually creates problems for the final user and it's better to create magazines that are readable "as is" instead of zooming in. Zoom for specific parts can be achieved normally with javascript (with tools like lightboxes). ;)

That said. You have likely to set a correct value to the meta tag `viewport`, you can google for it or see the documentation here:
https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

**Comment by Chrissmen** [comment]
ok thanks i resolve this issue with viewport meta in html, each page is needed changed, i send the issue to ajarproduction.com i hope they can resolve to the next versions
thanks

**Comment by folletto** [comment]
Excellent! Thanks. :)
