### ISSUE TITLE
iTunesConnect: should we add new issues into the iTunesConnect Newsstand?

### ISSUE THREAD

**Issue by divlv** [Simbul/baker#936]
To use Newsstand for subscriptions and updates I've enabled Newsstand in the 
iTunes Connect "Manage Newsstand" page.

But at once I've got a question regarding my future issues:
should I every time add a new issue here in iTunes (not only in Baker's Shelf), 
to make them available to download and/or purchase (In-App Purchase) through Baker ?

![Should I add new issues every time here?](http://is.gd/tkOxi0)

**Comment by folletto** [comment]
Yes. iTunes manages the Apple side of things, and that's the only way to have managed issues and purchases. Baker will load whatever exists in the `shelf.json` file, but if you don't add the issues there, you can't do in-app purchases because there are no ways for the Apple Store to validate them.

However, please use the Apple Developer Forum for these questions, since these are about Apple and not about Baker and we have limited time. Thanks. :)
