### ISSUE TITLE
Question regarding MagRocket/Baker Combo

### ISSUE THREAD

**Issue by MaverickWar** [Simbul/baker#950]
I have my magazine set up and i have a free subscription option, when i create a new issue in magrocket, it doesnt instantly pop up on subscribed users device that there is a new user and it doesn't automatically download the content...

Have i not set this up correctly somewhere or am i missing something, perhaps automatic content downloading in the background isnt an option but i thought this was a newsstand feature?

**Comment by nin9creative** [comment]
Right now it would only show up after the shelf is refreshed.

In order to accomplish what you expect below, Push Notifications with new content notifications has to be enabled.  Currently this 
feature is not supported by MagRocket.  It's on the list for a future release.  MagRocket is storing the APNS push notification tokens
if you have Push Notifications enabled in your application in iTunes Connect - however there currently is no way to send the notifications...

**Comment by nin9creative** [comment]
Just a clarification.

Baker would/does support it, but at this time you'd need to develop it yourself using something like Parse.com or Urban Airship.

I'm planning on adding the functionality into MagRocket based on Easy APNS, but like I said - its planned for a future release.

**Comment by MaverickWar** [comment]
Ok well lets hope this is something you can guys can get into in the future. It would be a cool feature.

**Comment by folletto** [comment]
If you can't wait for MagRocket you can add it yourself as @nin9creative was suggesting, since Baker's support is already there (and there are magazines out there that afaik are already using it). :)

Also, I'm sure that he would enjoy a pull request with the added feature. ;)
