### ISSUE TITLE
Auto renewable subscription does not unlock the magazine for download

### ISSUE THREAD

**Issue by kkporter** [Simbul/baker#967]
I wonder if you guys have seen any issues like this - especially when using non-MagRocket demo backend.

We encountered an issue with Baker 4.1 with Magrocket backend1.0.

We are developing a magazine with paid subscription under sandbox environment:
In our app, we
1. Successfully subscribed to a auto-renewable subscription
2. However issues not marked as "PURCHASED"
3. If I click to download issue (supposed to be purchased already), prompt to ask me to pay for single issue
3. No log in Purchase table and Receipt and Subscription table in Magrocket backend for this transaction

However, if i add back the user ID to the Purchase table, the issue would be marked as PURCHASED on my device and act normal.

This is what I observed a recent update from Appstore, they might have made a change to subscription process such that causing some kind of errors for backend to write user ID into the purchase and receipt and subscription table:

Originally the subscription process is as follows, messages on devices shown in the following order:
1a. "Confirm your Subscription - Do you want to subscribe to xxx Subscription for 1 year for $1.99? This Subscription will automatically renew until canceled."
2a. Loading and Subscribing
3a. "You are successfully subscribed."

For the latest subscription process is as follows, messages on devices shown in the following order:
1b. "Confirm your Subscription - Do you want to subscribe to xxx Subscription for 1 year for $1.99? This Subscription will automatically renew until canceled."
2b. At this point, there is an extra message pop up after confirming message to payment:
"Your 1-year subscription renews on 21 June 2013 for $1.99. To review subscription settings or cancel auto-renewal, tap Manage."
3b. Loading and Subscribing
4b. No message on successfully subscribed or errors.

Not sure whether the extra message 2b causing some kind of error with backend API, maybe an interruption so that the MarkIssuesAsPurchased function and the logs on Purchase/Receipt/Subscription Table are not working?

Strange thing is:
We have another product which is in online production, approved and currently in the Appstore, settings everything is the same, which does not have this issue. Another product, which we just started testing today, setting everything same as the online product, running in the same backend and api, encounter this issue.

Any ideas?

**Comment by nin9creative** [comment]
What happens if you create a new test user to use for the Subscription process?  Does the message change back to the first that you mentioned?

I've had another user with an issue in Production where for some reason the Receipt and Subscription are being logged, but the Purchase isn't being recorded for the user - which results in no issues being unlocked.  Trying to figure that out - but it seems that it's not a broad issue because I'm sure I would have heard a ton more chatter about it.

Hmmm...  Sucks because I've been on vacation and out of town this week and can't really test as I don't have my dev machine.

On Jun 21, 2013, at 02:03 PM, kkporter notifications@github.com wrote:

I wonder if you guys have seen any issues like this - especially when using non-MagRocket demo backend.
We encountered an issue with Baker 4.1 with Magrocket backend1.0.
We are developing a magazine with paid subscription under sandbox environment:
In our app, we
1. Successfully subscribed to a auto-renewable subscription
2. However issues not marked as "PURCHASED"
3. If I click to download issue (supposed to be purchased already), prompt to ask me to pay for single issue
3. No log in Purchase table and Receipt and Subscription table in Magrocket backend for this transaction
However, if i add back the user ID to the Purchase table, the issue would be marked as PURCHASED on my device and act normal.
This is what I observed a recent update from Appstore, they might have made a change to subscription process such that causing some kind of errors for backend to write user ID into the purchase and receipt and subscription table:
Originally the subscription process is as follows, messages on devices shown in the following order:
1a. "Confirm your Subscription - Do you want to subscribe to xxx Subscription for 1 year for $1.99? This Subscription will automatically renew until canceled."
2a. Loading and Subscribing
3a. "You are successfully subscribed."
For the latest subscription process is as follows, messages on devices shown in the following order:
1b. "Confirm your Subscription - Do you want to subscribe to xxx Subscription for 1 year for $1.99? This Subscription will automatically renew until canceled."
2b. At this point, there is an extra message pop up after confirming message to payment:
"Your 1-year subscription renews on 21 June 2013 for $1.99. To review subscription settings or cancel auto-renewal, tap Manage."
3b. Loading and Subscribing
4b. No message on successfully subscribed or errors.
Not sure whether the extra message 2b causing some kind of error with backend API, maybe an interruption so that the MarkIssuesAsPurchased function and the logs on Purchase/Receipt/Subscription Table are not working?
Strange thing is:
We have another product which is in online production, approved and currently in the Appstore, settings everything is the same, which does not have this issue. Another product, which we just started testing today, setting everything same as the online product, running in the same backend and api, encounter this issue.
Any ideas?

**Comment by kkporter** [comment]
Hey Andrew, 

Sorry to interrupt your vacation. I did tried that as well, creating a new test user at itunesconnect doesn't help. The problem is still same. With our new app in sandbox environment, subscribing message is still the second set and missed out with "successfully subscribed", and also didn't unlock the issues. And also this transaction not recorded with all the purchase/receipt/subscription table at the Magrocket backend.

Take your time for the investigation and enjoy the holiday!

Regards,
Porter

**Comment by nin9creative** [comment]
Are you sure the endpoints are correct in the Constants.h file?  

Can you see any messages being logged in the system log for MagRocket or in the baker output window?

Regards,
Andrew

**Comment by kkporter** [comment]
I think the endpoints are correct in the Constants.h file, because I can see the Subscription details, Subscription price, I can see the Free issue and Paid issue details, Issue Covers, and also be able to Download free issue and paid - single issue.

The log include the following messages in the Magrocket - System Logs 
-Retrieving issues for App ID
-Checking Purchase for App ID
-Storing APN token for App ID
-Confirming Purchase for App ID
-Verifying receipt with Apple for App ID
-Invalid receipt for App ID (error 21004)

thought the 21004 error is due to I am using same device to test with production and testing magazine?

The problem only occur with subscription and only happen with the latest project we are working on. 

We are using the same backend for another magazine which is in online production and in Appstore now and not having this problem.

Regards,
Porter

**Comment by nin9creative** [comment]
If the receipt isn't validated, nothing will be recorded in MagRocket....

Regards,
Andrew

**Comment by nin9creative** [comment]
21004
The shared secret you provided does not match the shared secret on file for your account.

Regards,
Andrew

**Comment by kkporter** [comment]
Ooo my bad.. the shared secret we carelessly include a space at the end. Now it's working fine! thanks! and I will close this ticket.

Would you mind to tell me if you put the error table somewhere so that we can check with the errors next time we encounter one?

Regards,
Porter

**Comment by nin9creative** [comment]
It's all in the InApp purchasing documentation from Apple.

http://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StoreKitGuide/RenewableSubscriptions/RenewableSubscriptions.html

Regards,
Andrew
