### ISSUE TITLE
Multiple periodicals, one app

### ISSUE THREAD

**Issue by douglance** [Simbul/baker#992]
I seem to remember a discussion about this previously here, though despite my best efforts I cannot find it now.

What is the feasibility of having multiple periodicals contained in a single app powered by Baker?

I run a company that publishes many similar magazines that are joined under a single brand. I would prefer to have all the magazines publish to a single app location. 

Thank you for your time and attention. 

-Doug

**Comment by folletto** [comment]
I think you're referring to issue #949. :)
But that discussion moved a bit from the initial question. :)

To answer specifically: you can have them inside a single Baker app if it's ok for you to have a single shelf for all of them. But there's no specific code to handle them separately or with a special visualization. That would be custom development that would involve the creation of a new shelf (the `BakerView` will likely stay the same).

On the other side, I would point out that:
1. Newsstand don't support multiple publications in one app, afaik. Because the concept there is "one app, one magazine".
2. You could do it in a separate app, but right now Baker doesn't support downloads in standalone mode. See issue #644 to track that feature.
3. Developing one app for multiple magazines seems reducing the effectiveness of the communications, since everyone will be inside that and you can't publicize each brand specifically and uniquely.

**Comment by douglance** [comment]
That fully answers my questions. Thanks!

**Comment by folletto** [comment]
You're welcome! :)
